// Code generated by goctl. DO NOT EDIT.
package types

type User struct {
	Id       int64  `json:"id"`
	Email    string `json:"email"`
	NickName string `json:"nickname"`
	Gender   string `json:"gender"`
	Age      int64  `json:"age"`
	Identity int64  `json:"identity"`
}

type RegisterReq struct {
	Email            string `json:"email"`
	Password         string `json:"password"`
	VerificationCode string `json:"verification_code"`
}

type RegisterResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type VerificationReq struct {
	Email string `json:"email"`
}

type VerfificationResp struct {
	VerficationCode string `json:"verfication_code"`
}

type LoginReq struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type UpdateInfoReq struct {
	NickName string `json:"nickname"`
	Gender   string `json:"gender"`
	Age      int64  `json:"age"`
}

type UpdateInfoResp struct {
	UserInfo User `json:"userInfo"`
}

type UserInfoReq struct {
}

type UserInfoResp struct {
	UserInfo User `json:"userInfo"`
}

type UpdatePSWReq struct {
	OldPassword     string `json:"old_password"`
	NewPassword     string `json:"new_password"`
	VerficationCode string `json:"verification_code"`
}

type UpdatePSWResp struct {
}

type UpdateIdentityReq struct {
	Id int64 `json:"id"`
}

type UpdateIdentityResp struct {
	User User `json:"user"`
}
