CREATE TABLE `diary`(
    `id` BIGINT UNSIGNED NOT NULL  AUTO_INCREMENT,
    `publisher_id` BIGINT UNSIGNED NOT NULL ,
    `picture_1` VARCHAR(255) NULL  DEFAULT '' COMMENT '图片1',
    `picture_2` VARCHAR(255) NULL  DEFAULT '' COMMENT '图片2',
    `picture_3` VARCHAR(255) NULL  DEFAULT '' COMMENT  '图片3',
    `content` TEXT NOT NULL COMMENT '日志内容',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `delete_time` DATETIME NULL ,
    PRIMARY KEY (`id`)
#     FOREIGN KEY (`published_id`) REFERENCES user(`id`)
)ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;