CREATE TABLE `images`(
    `id`BIGINT UNSIGNED NOT NULL  AUTO_INCREMENT,
    `type` VARCHAR(255) NOT NULL  DEFAULT '',
    `out_id` BIGINT UNSIGNED NOT NULL ,
    `url` TEXT NOT NULL ,
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `delete_time` DATETIME NULL ,
    PRIMARY KEY (`id`)
)ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;
