CREATE TABLE `like`(
    `id`BIGINT UNSIGNED NOT NULL  AUTO_INCREMENT,
    `user_id` BIGINT UNSIGNED NOT NULL ,
    `type` VARCHAR(255) NOT NULL ,
    `out_id` BIGINT UNSIGNED NOT NULL ,
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `delete_time` DATETIME NULL ,
    PRIMARY KEY (`id`),
    UNIQUE KEY `like_unique`(`user_id`,`type`,`out_id`)
)ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;