CREATE TABLE `message`(
 `id`BIGINT UNSIGNED NOT NULL  AUTO_INCREMENT,
 `sender_id` BIGINT UNSIGNED NOT NULL ,
 `receiver_id` BIGINT UNSIGNED NOT NULL ,
 `type` VARCHAR(255) NOT NULL DEFAULT 'text',
 `content` TEXT NOT NULL ,
 `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 `delete_time` DATETIME NULL ,
 PRIMARY KEY (`id`)
)