CREATE TABLE `tweet`(
    `id` BIGINT UNSIGNED NOT NULL  AUTO_INCREMENT,
    `publisher_id` BIGINT UNSIGNED NOT NULL,
    `content` TEXT NOT NULL ,
    `view_num` TEXT NOT NULL DEFAULT 0,
    `like_num` INT NOT NULL DEFAULT 0,
    `comment_num` INT NOT NULL DEFAULT 0,
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `delete_time` DATETIME NULL ,
     PRIMARY KEY (`id`)
)ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;