// Code generated by goctl. DO NOT EDIT.
// Source: starcenter.proto

package starcenter

import (
	"context"

	"LingXi/app/star/cmd/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	EnterStarRequest   = pb.EnterStarRequest
	EnterStarResponse  = pb.EnterStarResponse
	IfEnterRequest     = pb.IfEnterRequest
	IfEnterResponse    = pb.IfEnterResponse
	MyStarRequest      = pb.MyStarRequest
	MyStarResponse     = pb.MyStarResponse
	StarDetailRequest  = pb.StarDetailRequest
	StarDetailResponse = pb.StarDetailResponse

	Starcenter interface {
		EnterStar(ctx context.Context, in *EnterStarRequest, opts ...grpc.CallOption) (*EnterStarResponse, error)
		MyStar(ctx context.Context, in *MyStarRequest, opts ...grpc.CallOption) (*MyStarResponse, error)
		StarDetail(ctx context.Context, in *StarDetailRequest, opts ...grpc.CallOption) (*StarDetailResponse, error)
		IfEnter(ctx context.Context, in *IfEnterRequest, opts ...grpc.CallOption) (*IfEnterResponse, error)
	}

	defaultStarcenter struct {
		cli zrpc.Client
	}
)

func NewStarcenter(cli zrpc.Client) Starcenter {
	return &defaultStarcenter{
		cli: cli,
	}
}

func (m *defaultStarcenter) EnterStar(ctx context.Context, in *EnterStarRequest, opts ...grpc.CallOption) (*EnterStarResponse, error) {
	client := pb.NewStarcenterClient(m.cli.Conn())
	return client.EnterStar(ctx, in, opts...)
}

func (m *defaultStarcenter) MyStar(ctx context.Context, in *MyStarRequest, opts ...grpc.CallOption) (*MyStarResponse, error) {
	client := pb.NewStarcenterClient(m.cli.Conn())
	return client.MyStar(ctx, in, opts...)
}

func (m *defaultStarcenter) StarDetail(ctx context.Context, in *StarDetailRequest, opts ...grpc.CallOption) (*StarDetailResponse, error) {
	client := pb.NewStarcenterClient(m.cli.Conn())
	return client.StarDetail(ctx, in, opts...)
}

func (m *defaultStarcenter) IfEnter(ctx context.Context, in *IfEnterRequest, opts ...grpc.CallOption) (*IfEnterResponse, error) {
	client := pb.NewStarcenterClient(m.cli.Conn())
	return client.IfEnter(ctx, in, opts...)
}
