// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.22.2
// source: imagecenter.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ImageCenter_PostImage_FullMethodName    = "/pb.ImageCenter/postImage"
	ImageCenter_GetAllImages_FullMethodName = "/pb.ImageCenter/getAllImages"
	ImageCenter_GetDetail_FullMethodName    = "/pb.ImageCenter/getDetail"
	ImageCenter_DeleteImage_FullMethodName  = "/pb.ImageCenter/deleteImage"
	ImageCenter_GetOneImage_FullMethodName  = "/pb.ImageCenter/getOneImage"
)

// ImageCenterClient is the client API for ImageCenter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ImageCenterClient interface {
	PostImage(ctx context.Context, in *PostImageRequest, opts ...grpc.CallOption) (*PostImageResponse, error)
	GetAllImages(ctx context.Context, in *GetAllImagesRequest, opts ...grpc.CallOption) (*GetAllImagesResponse, error)
	GetDetail(ctx context.Context, in *GetDetailRequest, opts ...grpc.CallOption) (*GetDetailResponse, error)
	DeleteImage(ctx context.Context, in *DeleteImageRequest, opts ...grpc.CallOption) (*DeleteImageResponse, error)
	GetOneImage(ctx context.Context, in *GetOneImageRequest, opts ...grpc.CallOption) (*GetOneImageResponse, error)
}

type imageCenterClient struct {
	cc grpc.ClientConnInterface
}

func NewImageCenterClient(cc grpc.ClientConnInterface) ImageCenterClient {
	return &imageCenterClient{cc}
}

func (c *imageCenterClient) PostImage(ctx context.Context, in *PostImageRequest, opts ...grpc.CallOption) (*PostImageResponse, error) {
	out := new(PostImageResponse)
	err := c.cc.Invoke(ctx, ImageCenter_PostImage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageCenterClient) GetAllImages(ctx context.Context, in *GetAllImagesRequest, opts ...grpc.CallOption) (*GetAllImagesResponse, error) {
	out := new(GetAllImagesResponse)
	err := c.cc.Invoke(ctx, ImageCenter_GetAllImages_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageCenterClient) GetDetail(ctx context.Context, in *GetDetailRequest, opts ...grpc.CallOption) (*GetDetailResponse, error) {
	out := new(GetDetailResponse)
	err := c.cc.Invoke(ctx, ImageCenter_GetDetail_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageCenterClient) DeleteImage(ctx context.Context, in *DeleteImageRequest, opts ...grpc.CallOption) (*DeleteImageResponse, error) {
	out := new(DeleteImageResponse)
	err := c.cc.Invoke(ctx, ImageCenter_DeleteImage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageCenterClient) GetOneImage(ctx context.Context, in *GetOneImageRequest, opts ...grpc.CallOption) (*GetOneImageResponse, error) {
	out := new(GetOneImageResponse)
	err := c.cc.Invoke(ctx, ImageCenter_GetOneImage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ImageCenterServer is the server API for ImageCenter service.
// All implementations must embed UnimplementedImageCenterServer
// for forward compatibility
type ImageCenterServer interface {
	PostImage(context.Context, *PostImageRequest) (*PostImageResponse, error)
	GetAllImages(context.Context, *GetAllImagesRequest) (*GetAllImagesResponse, error)
	GetDetail(context.Context, *GetDetailRequest) (*GetDetailResponse, error)
	DeleteImage(context.Context, *DeleteImageRequest) (*DeleteImageResponse, error)
	GetOneImage(context.Context, *GetOneImageRequest) (*GetOneImageResponse, error)
	mustEmbedUnimplementedImageCenterServer()
}

// UnimplementedImageCenterServer must be embedded to have forward compatible implementations.
type UnimplementedImageCenterServer struct {
}

func (UnimplementedImageCenterServer) PostImage(context.Context, *PostImageRequest) (*PostImageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostImage not implemented")
}
func (UnimplementedImageCenterServer) GetAllImages(context.Context, *GetAllImagesRequest) (*GetAllImagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllImages not implemented")
}
func (UnimplementedImageCenterServer) GetDetail(context.Context, *GetDetailRequest) (*GetDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDetail not implemented")
}
func (UnimplementedImageCenterServer) DeleteImage(context.Context, *DeleteImageRequest) (*DeleteImageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteImage not implemented")
}
func (UnimplementedImageCenterServer) GetOneImage(context.Context, *GetOneImageRequest) (*GetOneImageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOneImage not implemented")
}
func (UnimplementedImageCenterServer) mustEmbedUnimplementedImageCenterServer() {}

// UnsafeImageCenterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ImageCenterServer will
// result in compilation errors.
type UnsafeImageCenterServer interface {
	mustEmbedUnimplementedImageCenterServer()
}

func RegisterImageCenterServer(s grpc.ServiceRegistrar, srv ImageCenterServer) {
	s.RegisterService(&ImageCenter_ServiceDesc, srv)
}

func _ImageCenter_PostImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageCenterServer).PostImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImageCenter_PostImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageCenterServer).PostImage(ctx, req.(*PostImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImageCenter_GetAllImages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllImagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageCenterServer).GetAllImages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImageCenter_GetAllImages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageCenterServer).GetAllImages(ctx, req.(*GetAllImagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImageCenter_GetDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageCenterServer).GetDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImageCenter_GetDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageCenterServer).GetDetail(ctx, req.(*GetDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImageCenter_DeleteImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageCenterServer).DeleteImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImageCenter_DeleteImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageCenterServer).DeleteImage(ctx, req.(*DeleteImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImageCenter_GetOneImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOneImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageCenterServer).GetOneImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImageCenter_GetOneImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageCenterServer).GetOneImage(ctx, req.(*GetOneImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ImageCenter_ServiceDesc is the grpc.ServiceDesc for ImageCenter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ImageCenter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.ImageCenter",
	HandlerType: (*ImageCenterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "postImage",
			Handler:    _ImageCenter_PostImage_Handler,
		},
		{
			MethodName: "getAllImages",
			Handler:    _ImageCenter_GetAllImages_Handler,
		},
		{
			MethodName: "getDetail",
			Handler:    _ImageCenter_GetDetail_Handler,
		},
		{
			MethodName: "deleteImage",
			Handler:    _ImageCenter_DeleteImage_Handler,
		},
		{
			MethodName: "getOneImage",
			Handler:    _ImageCenter_GetOneImage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "imagecenter.proto",
}
