// Code generated by goctl. DO NOT EDIT.
package types

type EnterRequest struct {
	StarId int64 `json:"starId"`
}

type EnterResponse struct {
	UserId  int64  `json:"userId"`
	StarNam string `json:"starNam"`
}

type MyStarsRequest struct {
}

type MyStarsResponse struct {
	Star []string `json:"star"`
}

type StarDetailRequest struct {
	StarId int64 `path:"starId"`
}

type StarDetailResponse struct {
	Name        string `json:"name"`
	PeopleCount int    `json:"peopleCount"`
}

type IfEnterRequest struct {
	StarId int64 `path:"starId"`
}

type IfEnterResponse struct {
	Enter bool `json:"enter"`
}
