// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"time"

	"github.com/SpectatorNan/gorm-zero/gormc"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"gorm.io/gorm"
)

var (
	cacheDiaryIdPrefix = "cache:diary:id:"
)

type (
	diaryModel interface {
		Insert(ctx context.Context, tx *gorm.DB, data *Diary) error

		FindOne(ctx context.Context, id int64) (*Diary, error)
		Update(ctx context.Context, tx *gorm.DB, data *Diary) error

		Delete(ctx context.Context, tx *gorm.DB, id int64) error
		Transaction(ctx context.Context, fn func(db *gorm.DB) error) error
	}

	defaultDiaryModel struct {
		gormc.CachedConn
		table string
	}

	Diary struct {
		Id          int64        `gorm:"column:id"`
		PublisherId int64        `gorm:"column:published_id"`
		Picture1    string       `gorm:"column:picture_1"` // 图片1
		Picture2    string       `gorm:"column:picture_2"` // 图片2
		Picture3    string       `gorm:"column:picture_3"` // 图片3
		Content     string       `gorm:"column:content"`   // 日志内容
		CreateTime  time.Time    `gorm:"column:create_time"`
		UpdateTime  time.Time    `gorm:"column:update_time"`
		DeleteTime  sql.NullTime `gorm:"column:delete_time"`
	}
)

func (Diary) TableName() string {
	return "`diary`"
}

func newDiaryModel(conn *gorm.DB, c cache.CacheConf) *defaultDiaryModel {
	return &defaultDiaryModel{
		CachedConn: gormc.NewConn(conn, c),
		table:      "`diary`",
	}
}

func (m *defaultDiaryModel) Insert(ctx context.Context, tx *gorm.DB, data *Diary) error {

	err := m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Save(&data).Error
	}, m.getCacheKeys(data)...)
	return err
}

func (m *defaultDiaryModel) FindOne(ctx context.Context, id int64) (*Diary, error) {
	diaryIdKey := fmt.Sprintf("%s%v", cacheDiaryIdPrefix, id)
	var resp Diary
	err := m.QueryCtx(ctx, &resp, diaryIdKey, func(conn *gorm.DB, v interface{}) error {
		return conn.Model(&Diary{}).Where("`id` = ?", id).First(&resp).Error
	})
	switch err {
	case nil:
		return &resp, nil
	case gormc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultDiaryModel) Update(ctx context.Context, tx *gorm.DB, data *Diary) error {
	old, err := m.FindOne(ctx, data.Id)
	if err != nil && err != ErrNotFound {
		return err
	}
	err = m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Save(data).Error
	}, m.getCacheKeys(old)...)
	return err
}

func (m *defaultDiaryModel) getCacheKeys(data *Diary) []string {
	if data == nil {
		return []string{}
	}
	diaryIdKey := fmt.Sprintf("%s%v", cacheDiaryIdPrefix, data.Id)
	cacheKeys := []string{
		diaryIdKey,
	}
	cacheKeys = append(cacheKeys, m.customCacheKeys(data)...)
	return cacheKeys
}

func (m *defaultDiaryModel) Delete(ctx context.Context, tx *gorm.DB, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		if err == ErrNotFound {
			return nil
		}
		return err
	}
	err = m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Delete(&Diary{}, id).Error
	}, m.getCacheKeys(data)...)
	return err
}

func (m *defaultDiaryModel) Transaction(ctx context.Context, fn func(db *gorm.DB) error) error {
	return m.TransactCtx(ctx, fn)
}

func (m *defaultDiaryModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheDiaryIdPrefix, primary)
}

func (m *defaultDiaryModel) queryPrimary(conn *gorm.DB, v, primary interface{}) error {
	return conn.Model(&Diary{}).Where("`id` = ?", primary).Take(v).Error
}
