// Code generated by goctl. DO NOT EDIT.
package types

type Post struct {
	PostId          int64       `json:"postId"`
	PublisherId     int64       `json:"publisherId"`
	PublisherName   string      `json:"publisherName"`
	PublisherAvatar string      `json:"publisherAvatar"`
	Category        string      `json:"category"`
	Content         string      `json:"content"`
	ViewNum         int64       `json:"viewNum"`
	LikeNum         int64       `json:"likeNum"`
	CommentNum      int64       `json:"commentNum"`
	PostImage       []PostImage `json:"postImage"`
	Time            string      `json:"time"`
}

type PostComment struct {
	CommentId       int64          `json:"commentId"`
	PublisherId     int64          `json:"publisherId"`
	PubliserName    string         `json:"publisherName"`
	PublisherAvatar string         `json:"publisherAvatar"`
	PostId          int64          `json:"postId"`
	CommentImage    []CommentImage `json:"commentImage"`
	Content         string         `json:"content"`
	Time            string         `json:"time"`
}

type PostImage struct {
	PostId  int64  `json:"postId"`
	ImageId int64  `json:"imageId"`
	Url     string `json:"url"`
}

type CommentImage struct {
	CommentId int64  `json:"commentId"`
	ImageId   int64  `json:"imageId"`
	Url       string `json:"url"`
}

type PostRequest struct {
	Category string `json:"category"`
	Content  string `json:"content"`
}

type PostResponse struct {
	Post Post `json:"post"`
}

type GetPostRequest struct {
}

type GetPostResponse struct {
	Post []Post `json:"post"`
}

type GetCategoryPostRequest struct {
	Category string `path:"category"`
}

type GetCategoryPostResponse struct {
	Post []Post `json:"post"`
}

type PersonalPostRequest struct {
	Category string `path:"category"`
}

type PersonalPostResponse struct {
	Post []Post `json:"post"`
}

type GetDetailRequest struct {
	PostId int64 `path:"postId"`
}

type GetDetailResponse struct {
	Post Post `json:"post"`
}

type DeletePostRequest struct {
	PostId int64 `path:"postId"`
}

type DeletePostResponse struct {
	PostId int64 `json:"postId"`
}

type CommentPostRequest struct {
	PostId  int64  `json:"postId"`
	Content string `json:"content"`
}

type CommentPostResponse struct {
	PostComment PostComment `json:"postComment"`
}

type GetCommentsRequst struct {
	PostId int64 `path:"postId"`
}

type GetCommentsResponse struct {
	PostComment []PostComment `json:"postComment"`
}

type DeleteCommentRequest struct {
	CommentId int64 `path:"commentId"`
}

type DeleteCommentResponse struct {
	CommentId int64 `path:"commentId"`
}

type UploadImageRequest struct {
	PostId   int64  `json:"postId"`
	ImageUrl string `json:"imageUrl"`
}

type UploadImageResponse struct {
	PostImage PostImage `json:"postImage"`
}

type ViewPostRequest struct {
	PostId int64 `json:"postId"`
}

type ViewPostResponse struct {
	PostId int64 `json:"postId"`
}

type LikePostRequest struct {
	PostId int64 `json:"postId"`
}

type LikePostResponse struct {
	PostId int64 `json:"postId"`
}

type CancelLikeRequest struct {
	PostId int64 `json:"postId"`
}

type CancelLikeResponse struct {
	PostId int64 `json:"postId"`
}

type IfLikeRequest struct {
	PostId int64 `path:"postId"`
}

type IfLikeResponse struct {
	Like bool `json:"like"`
}
