// Code generated by goctl. DO NOT EDIT.
// Source: comment.proto

package commentcenter

import (
	"context"

	"LingXi/app/comment/cmd/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Comment               = pb.Comment
	CommentRequest        = pb.CommentRequest
	CommentResponse       = pb.CommentResponse
	DeleteCommentRequest  = pb.DeleteCommentRequest
	DeleteCommentResponse = pb.DeleteCommentResponse
	GetCommentRequest     = pb.GetCommentRequest
	GetCommentResponse    = pb.GetCommentResponse

	CommentCenter interface {
		PostComment(ctx context.Context, in *CommentRequest, opts ...grpc.CallOption) (*CommentResponse, error)
		GetComments(ctx context.Context, in *GetCommentRequest, opts ...grpc.CallOption) (*GetCommentResponse, error)
		DeleteComment(ctx context.Context, in *DeleteCommentRequest, opts ...grpc.CallOption) (*DeleteCommentResponse, error)
	}

	defaultCommentCenter struct {
		cli zrpc.Client
	}
)

func NewCommentCenter(cli zrpc.Client) CommentCenter {
	return &defaultCommentCenter{
		cli: cli,
	}
}

func (m *defaultCommentCenter) PostComment(ctx context.Context, in *CommentRequest, opts ...grpc.CallOption) (*CommentResponse, error) {
	client := pb.NewCommentCenterClient(m.cli.Conn())
	return client.PostComment(ctx, in, opts...)
}

func (m *defaultCommentCenter) GetComments(ctx context.Context, in *GetCommentRequest, opts ...grpc.CallOption) (*GetCommentResponse, error) {
	client := pb.NewCommentCenterClient(m.cli.Conn())
	return client.GetComments(ctx, in, opts...)
}

func (m *defaultCommentCenter) DeleteComment(ctx context.Context, in *DeleteCommentRequest, opts ...grpc.CallOption) (*DeleteCommentResponse, error) {
	client := pb.NewCommentCenterClient(m.cli.Conn())
	return client.DeleteComment(ctx, in, opts...)
}
