// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.22.2
// source: starcenter.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnterStarRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	StarId int64 `protobuf:"varint,2,opt,name=StarId,proto3" json:"StarId,omitempty"`
}

func (x *EnterStarRequest) Reset() {
	*x = EnterStarRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_starcenter_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnterStarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterStarRequest) ProtoMessage() {}

func (x *EnterStarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_starcenter_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterStarRequest.ProtoReflect.Descriptor instead.
func (*EnterStarRequest) Descriptor() ([]byte, []int) {
	return file_starcenter_proto_rawDescGZIP(), []int{0}
}

func (x *EnterStarRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *EnterStarRequest) GetStarId() int64 {
	if x != nil {
		return x.StarId
	}
	return 0
}

type EnterStarResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   int64  `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	StarName string `protobuf:"bytes,2,opt,name=StarName,proto3" json:"StarName,omitempty"`
}

func (x *EnterStarResponse) Reset() {
	*x = EnterStarResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_starcenter_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnterStarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterStarResponse) ProtoMessage() {}

func (x *EnterStarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_starcenter_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterStarResponse.ProtoReflect.Descriptor instead.
func (*EnterStarResponse) Descriptor() ([]byte, []int) {
	return file_starcenter_proto_rawDescGZIP(), []int{1}
}

func (x *EnterStarResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *EnterStarResponse) GetStarName() string {
	if x != nil {
		return x.StarName
	}
	return ""
}

type MyStarRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
}

func (x *MyStarRequest) Reset() {
	*x = MyStarRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_starcenter_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MyStarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyStarRequest) ProtoMessage() {}

func (x *MyStarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_starcenter_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyStarRequest.ProtoReflect.Descriptor instead.
func (*MyStarRequest) Descriptor() ([]byte, []int) {
	return file_starcenter_proto_rawDescGZIP(), []int{2}
}

func (x *MyStarRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type MyStarResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Star []string `protobuf:"bytes,1,rep,name=Star,proto3" json:"Star,omitempty"`
}

func (x *MyStarResponse) Reset() {
	*x = MyStarResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_starcenter_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MyStarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyStarResponse) ProtoMessage() {}

func (x *MyStarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_starcenter_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyStarResponse.ProtoReflect.Descriptor instead.
func (*MyStarResponse) Descriptor() ([]byte, []int) {
	return file_starcenter_proto_rawDescGZIP(), []int{3}
}

func (x *MyStarResponse) GetStar() []string {
	if x != nil {
		return x.Star
	}
	return nil
}

type StarDetailRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StarId int64 `protobuf:"varint,1,opt,name=StarId,proto3" json:"StarId,omitempty"`
}

func (x *StarDetailRequest) Reset() {
	*x = StarDetailRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_starcenter_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StarDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StarDetailRequest) ProtoMessage() {}

func (x *StarDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_starcenter_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StarDetailRequest.ProtoReflect.Descriptor instead.
func (*StarDetailRequest) Descriptor() ([]byte, []int) {
	return file_starcenter_proto_rawDescGZIP(), []int{4}
}

func (x *StarDetailRequest) GetStarId() int64 {
	if x != nil {
		return x.StarId
	}
	return 0
}

type StarDetailResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	People int64  `protobuf:"varint,2,opt,name=People,proto3" json:"People,omitempty"`
}

func (x *StarDetailResponse) Reset() {
	*x = StarDetailResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_starcenter_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StarDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StarDetailResponse) ProtoMessage() {}

func (x *StarDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_starcenter_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StarDetailResponse.ProtoReflect.Descriptor instead.
func (*StarDetailResponse) Descriptor() ([]byte, []int) {
	return file_starcenter_proto_rawDescGZIP(), []int{5}
}

func (x *StarDetailResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StarDetailResponse) GetPeople() int64 {
	if x != nil {
		return x.People
	}
	return 0
}

type IfEnterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	StarId int64 `protobuf:"varint,2,opt,name=StarId,proto3" json:"StarId,omitempty"`
}

func (x *IfEnterRequest) Reset() {
	*x = IfEnterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_starcenter_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IfEnterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IfEnterRequest) ProtoMessage() {}

func (x *IfEnterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_starcenter_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IfEnterRequest.ProtoReflect.Descriptor instead.
func (*IfEnterRequest) Descriptor() ([]byte, []int) {
	return file_starcenter_proto_rawDescGZIP(), []int{6}
}

func (x *IfEnterRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *IfEnterRequest) GetStarId() int64 {
	if x != nil {
		return x.StarId
	}
	return 0
}

type IfEnterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Enter bool `protobuf:"varint,1,opt,name=Enter,proto3" json:"Enter,omitempty"`
}

func (x *IfEnterResponse) Reset() {
	*x = IfEnterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_starcenter_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IfEnterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IfEnterResponse) ProtoMessage() {}

func (x *IfEnterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_starcenter_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IfEnterResponse.ProtoReflect.Descriptor instead.
func (*IfEnterResponse) Descriptor() ([]byte, []int) {
	return file_starcenter_proto_rawDescGZIP(), []int{7}
}

func (x *IfEnterResponse) GetEnter() bool {
	if x != nil {
		return x.Enter
	}
	return false
}

var File_starcenter_proto protoreflect.FileDescriptor

var file_starcenter_proto_rawDesc = []byte{
	0x0a, 0x10, 0x73, 0x74, 0x61, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x42, 0x0a, 0x10, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x53,
	0x74, 0x61, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x53, 0x74, 0x61, 0x72, 0x49, 0x64, 0x22, 0x47, 0x0a, 0x11, 0x45, 0x6e,
	0x74, 0x65, 0x72, 0x53, 0x74, 0x61, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x74, 0x61, 0x72, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x53, 0x74, 0x61, 0x72, 0x4e,
	0x61, 0x6d, 0x65, 0x22, 0x27, 0x0a, 0x0d, 0x4d, 0x79, 0x53, 0x74, 0x61, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x24, 0x0a, 0x0e,
	0x4d, 0x79, 0x53, 0x74, 0x61, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x53, 0x74, 0x61, 0x72, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x53, 0x74,
	0x61, 0x72, 0x22, 0x2b, 0x0a, 0x11, 0x53, 0x74, 0x61, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x72, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x53, 0x74, 0x61, 0x72, 0x49, 0x64, 0x22,
	0x40, 0x0a, 0x12, 0x53, 0x74, 0x61, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x65, 0x6f,
	0x70, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x50, 0x65, 0x6f, 0x70, 0x6c,
	0x65, 0x22, 0x40, 0x0a, 0x0e, 0x49, 0x66, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x53,
	0x74, 0x61, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x53, 0x74, 0x61,
	0x72, 0x49, 0x64, 0x22, 0x27, 0x0a, 0x0f, 0x49, 0x66, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x32, 0xe8, 0x01, 0x0a,
	0x0a, 0x73, 0x74, 0x61, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x12, 0x38, 0x0a, 0x09, 0x65,
	0x6e, 0x74, 0x65, 0x72, 0x53, 0x74, 0x61, 0x72, 0x12, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x6e,
	0x74, 0x65, 0x72, 0x53, 0x74, 0x61, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15,
	0x2e, 0x70, 0x62, 0x2e, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x53, 0x74, 0x61, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x06, 0x6d, 0x79, 0x53, 0x74, 0x61, 0x72, 0x12,
	0x11, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x79, 0x53, 0x74, 0x61, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x79, 0x53, 0x74, 0x61, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x12, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x70, 0x62,
	0x2e, 0x53, 0x74, 0x61, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x07, 0x69, 0x66, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x12, 0x12,
	0x2e, 0x70, 0x62, 0x2e, 0x49, 0x66, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x49, 0x66, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_starcenter_proto_rawDescOnce sync.Once
	file_starcenter_proto_rawDescData = file_starcenter_proto_rawDesc
)

func file_starcenter_proto_rawDescGZIP() []byte {
	file_starcenter_proto_rawDescOnce.Do(func() {
		file_starcenter_proto_rawDescData = protoimpl.X.CompressGZIP(file_starcenter_proto_rawDescData)
	})
	return file_starcenter_proto_rawDescData
}

var file_starcenter_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_starcenter_proto_goTypes = []interface{}{
	(*EnterStarRequest)(nil),   // 0: pb.EnterStarRequest
	(*EnterStarResponse)(nil),  // 1: pb.EnterStarResponse
	(*MyStarRequest)(nil),      // 2: pb.MyStarRequest
	(*MyStarResponse)(nil),     // 3: pb.MyStarResponse
	(*StarDetailRequest)(nil),  // 4: pb.StarDetailRequest
	(*StarDetailResponse)(nil), // 5: pb.StarDetailResponse
	(*IfEnterRequest)(nil),     // 6: pb.IfEnterRequest
	(*IfEnterResponse)(nil),    // 7: pb.IfEnterResponse
}
var file_starcenter_proto_depIdxs = []int32{
	0, // 0: pb.starcenter.enterStar:input_type -> pb.EnterStarRequest
	2, // 1: pb.starcenter.myStar:input_type -> pb.MyStarRequest
	4, // 2: pb.starcenter.starDetail:input_type -> pb.StarDetailRequest
	6, // 3: pb.starcenter.ifEnter:input_type -> pb.IfEnterRequest
	1, // 4: pb.starcenter.enterStar:output_type -> pb.EnterStarResponse
	3, // 5: pb.starcenter.myStar:output_type -> pb.MyStarResponse
	5, // 6: pb.starcenter.starDetail:output_type -> pb.StarDetailResponse
	7, // 7: pb.starcenter.ifEnter:output_type -> pb.IfEnterResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_starcenter_proto_init() }
func file_starcenter_proto_init() {
	if File_starcenter_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_starcenter_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnterStarRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_starcenter_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnterStarResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_starcenter_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MyStarRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_starcenter_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MyStarResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_starcenter_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StarDetailRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_starcenter_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StarDetailResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_starcenter_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IfEnterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_starcenter_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IfEnterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_starcenter_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_starcenter_proto_goTypes,
		DependencyIndexes: file_starcenter_proto_depIdxs,
		MessageInfos:      file_starcenter_proto_msgTypes,
	}.Build()
	File_starcenter_proto = out.File
	file_starcenter_proto_rawDesc = nil
	file_starcenter_proto_goTypes = nil
	file_starcenter_proto_depIdxs = nil
}
