// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.22.2
// source: starcenter.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Starcenter_EnterStar_FullMethodName  = "/pb.starcenter/enterStar"
	Starcenter_MyStar_FullMethodName     = "/pb.starcenter/myStar"
	Starcenter_StarDetail_FullMethodName = "/pb.starcenter/starDetail"
	Starcenter_IfEnter_FullMethodName    = "/pb.starcenter/ifEnter"
)

// StarcenterClient is the client API for Starcenter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StarcenterClient interface {
	EnterStar(ctx context.Context, in *EnterStarRequest, opts ...grpc.CallOption) (*EnterStarResponse, error)
	MyStar(ctx context.Context, in *MyStarRequest, opts ...grpc.CallOption) (*MyStarResponse, error)
	StarDetail(ctx context.Context, in *StarDetailRequest, opts ...grpc.CallOption) (*StarDetailResponse, error)
	IfEnter(ctx context.Context, in *IfEnterRequest, opts ...grpc.CallOption) (*IfEnterResponse, error)
}

type starcenterClient struct {
	cc grpc.ClientConnInterface
}

func NewStarcenterClient(cc grpc.ClientConnInterface) StarcenterClient {
	return &starcenterClient{cc}
}

func (c *starcenterClient) EnterStar(ctx context.Context, in *EnterStarRequest, opts ...grpc.CallOption) (*EnterStarResponse, error) {
	out := new(EnterStarResponse)
	err := c.cc.Invoke(ctx, Starcenter_EnterStar_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *starcenterClient) MyStar(ctx context.Context, in *MyStarRequest, opts ...grpc.CallOption) (*MyStarResponse, error) {
	out := new(MyStarResponse)
	err := c.cc.Invoke(ctx, Starcenter_MyStar_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *starcenterClient) StarDetail(ctx context.Context, in *StarDetailRequest, opts ...grpc.CallOption) (*StarDetailResponse, error) {
	out := new(StarDetailResponse)
	err := c.cc.Invoke(ctx, Starcenter_StarDetail_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *starcenterClient) IfEnter(ctx context.Context, in *IfEnterRequest, opts ...grpc.CallOption) (*IfEnterResponse, error) {
	out := new(IfEnterResponse)
	err := c.cc.Invoke(ctx, Starcenter_IfEnter_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StarcenterServer is the server API for Starcenter service.
// All implementations must embed UnimplementedStarcenterServer
// for forward compatibility
type StarcenterServer interface {
	EnterStar(context.Context, *EnterStarRequest) (*EnterStarResponse, error)
	MyStar(context.Context, *MyStarRequest) (*MyStarResponse, error)
	StarDetail(context.Context, *StarDetailRequest) (*StarDetailResponse, error)
	IfEnter(context.Context, *IfEnterRequest) (*IfEnterResponse, error)
	mustEmbedUnimplementedStarcenterServer()
}

// UnimplementedStarcenterServer must be embedded to have forward compatible implementations.
type UnimplementedStarcenterServer struct {
}

func (UnimplementedStarcenterServer) EnterStar(context.Context, *EnterStarRequest) (*EnterStarResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnterStar not implemented")
}
func (UnimplementedStarcenterServer) MyStar(context.Context, *MyStarRequest) (*MyStarResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MyStar not implemented")
}
func (UnimplementedStarcenterServer) StarDetail(context.Context, *StarDetailRequest) (*StarDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StarDetail not implemented")
}
func (UnimplementedStarcenterServer) IfEnter(context.Context, *IfEnterRequest) (*IfEnterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IfEnter not implemented")
}
func (UnimplementedStarcenterServer) mustEmbedUnimplementedStarcenterServer() {}

// UnsafeStarcenterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StarcenterServer will
// result in compilation errors.
type UnsafeStarcenterServer interface {
	mustEmbedUnimplementedStarcenterServer()
}

func RegisterStarcenterServer(s grpc.ServiceRegistrar, srv StarcenterServer) {
	s.RegisterService(&Starcenter_ServiceDesc, srv)
}

func _Starcenter_EnterStar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnterStarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StarcenterServer).EnterStar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Starcenter_EnterStar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StarcenterServer).EnterStar(ctx, req.(*EnterStarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Starcenter_MyStar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MyStarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StarcenterServer).MyStar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Starcenter_MyStar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StarcenterServer).MyStar(ctx, req.(*MyStarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Starcenter_StarDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StarDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StarcenterServer).StarDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Starcenter_StarDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StarcenterServer).StarDetail(ctx, req.(*StarDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Starcenter_IfEnter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IfEnterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StarcenterServer).IfEnter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Starcenter_IfEnter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StarcenterServer).IfEnter(ctx, req.(*IfEnterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Starcenter_ServiceDesc is the grpc.ServiceDesc for Starcenter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Starcenter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.starcenter",
	HandlerType: (*StarcenterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "enterStar",
			Handler:    _Starcenter_EnterStar_Handler,
		},
		{
			MethodName: "myStar",
			Handler:    _Starcenter_MyStar_Handler,
		},
		{
			MethodName: "starDetail",
			Handler:    _Starcenter_StarDetail_Handler,
		},
		{
			MethodName: "ifEnter",
			Handler:    _Starcenter_IfEnter_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "starcenter.proto",
}
