// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"fmt"

	"github.com/SpectatorNan/gorm-zero/gormc"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"gorm.io/gorm"
)

var (
	cacheStarsIdPrefix = "cache:stars:id:"
)

type (
	starsModel interface {
		Insert(ctx context.Context, tx *gorm.DB, data *Stars) error

		FindOne(ctx context.Context, id int64) (*Stars, error)
		Update(ctx context.Context, tx *gorm.DB, data *Stars) error

		Delete(ctx context.Context, tx *gorm.DB, id int64) error
		Transaction(ctx context.Context, fn func(db *gorm.DB) error) error
	}

	defaultStarsModel struct {
		gormc.CachedConn
		table string
	}

	Stars struct {
		Id          int64  `gorm:"column:id"`
		StarName    string `gorm:"column:star_name"`
		PeopleCount int64  `gorm:"column:people_count"`
	}
)

func (Stars) TableName() string {
	return "`stars`"
}

func newStarsModel(conn *gorm.DB, c cache.CacheConf) *defaultStarsModel {
	return &defaultStarsModel{
		CachedConn: gormc.NewConn(conn, c),
		table:      "`stars`",
	}
}

func (m *defaultStarsModel) Insert(ctx context.Context, tx *gorm.DB, data *Stars) error {

	err := m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Save(&data).Error
	}, m.getCacheKeys(data)...)
	return err
}

func (m *defaultStarsModel) FindOne(ctx context.Context, id int64) (*Stars, error) {
	starsIdKey := fmt.Sprintf("%s%v", cacheStarsIdPrefix, id)
	var resp Stars
	err := m.QueryCtx(ctx, &resp, starsIdKey, func(conn *gorm.DB, v interface{}) error {
		return conn.Model(&Stars{}).Where("`id` = ?", id).First(&resp).Error
	})
	switch err {
	case nil:
		return &resp, nil
	case gormc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultStarsModel) Update(ctx context.Context, tx *gorm.DB, data *Stars) error {
	old, err := m.FindOne(ctx, data.Id)
	if err != nil && err != ErrNotFound {
		return err
	}
	err = m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Save(data).Error
	}, m.getCacheKeys(old)...)
	return err
}

func (m *defaultStarsModel) getCacheKeys(data *Stars) []string {
	if data == nil {
		return []string{}
	}
	starsIdKey := fmt.Sprintf("%s%v", cacheStarsIdPrefix, data.Id)
	cacheKeys := []string{
		starsIdKey,
	}
	cacheKeys = append(cacheKeys, m.customCacheKeys(data)...)
	return cacheKeys
}

func (m *defaultStarsModel) Delete(ctx context.Context, tx *gorm.DB, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		if err == ErrNotFound {
			return nil
		}
		return err
	}
	err = m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Delete(&Stars{}, id).Error
	}, m.getCacheKeys(data)...)
	return err
}

func (m *defaultStarsModel) Transaction(ctx context.Context, fn func(db *gorm.DB) error) error {
	return m.TransactCtx(ctx, fn)
}

func (m *defaultStarsModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheStarsIdPrefix, primary)
}

func (m *defaultStarsModel) queryPrimary(conn *gorm.DB, v, primary interface{}) error {
	return conn.Model(&Stars{}).Where("`id` = ?", primary).Take(v).Error
}
