// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"fmt"

	"github.com/SpectatorNan/gorm-zero/gormc"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"gorm.io/gorm"
)

var (
	cacheUserStarIdPrefix           = "cache:userStar:id:"
	cacheUserStarUserIdStarIdPrefix = "cache:userStar:userId:starId:"
)

type (
	userStarModel interface {
		Insert(ctx context.Context, tx *gorm.DB, data *UserStar) error

		FindOne(ctx context.Context, id int64) (*UserStar, error)
		FindOneByUserIdStarId(ctx context.Context, userId int64, starId int64) (*UserStar, error)
		Update(ctx context.Context, tx *gorm.DB, data *UserStar) error

		Delete(ctx context.Context, tx *gorm.DB, id int64) error
		Transaction(ctx context.Context, fn func(db *gorm.DB) error) error
	}

	defaultUserStarModel struct {
		gormc.CachedConn
		table string
	}

	UserStar struct {
		Id     int64 `gorm:"column:id"`
		UserId int64 `gorm:"column:user_id"`
		StarId int64 `gorm:"column:star_id"`
	}
)

func (UserStar) TableName() string {
	return "`user_star`"
}

func newUserStarModel(conn *gorm.DB, c cache.CacheConf) *defaultUserStarModel {
	return &defaultUserStarModel{
		CachedConn: gormc.NewConn(conn, c),
		table:      "`user_star`",
	}
}

func (m *defaultUserStarModel) Insert(ctx context.Context, tx *gorm.DB, data *UserStar) error {

	err := m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Save(&data).Error
	}, m.getCacheKeys(data)...)
	return err
}

func (m *defaultUserStarModel) FindOne(ctx context.Context, id int64) (*UserStar, error) {
	userStarIdKey := fmt.Sprintf("%s%v", cacheUserStarIdPrefix, id)
	var resp UserStar
	err := m.QueryCtx(ctx, &resp, userStarIdKey, func(conn *gorm.DB, v interface{}) error {
		return conn.Model(&UserStar{}).Where("`id` = ?", id).First(&resp).Error
	})
	switch err {
	case nil:
		return &resp, nil
	case gormc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserStarModel) FindOneByUserIdStarId(ctx context.Context, userId int64, starId int64) (*UserStar, error) {
	userStarUserIdStarIdKey := fmt.Sprintf("%s%v:%v", cacheUserStarUserIdStarIdPrefix, userId, starId)
	var resp UserStar
	err := m.QueryRowIndexCtx(ctx, &resp, userStarUserIdStarIdKey, m.formatPrimary, func(conn *gorm.DB, v interface{}) (interface{}, error) {
		if err := conn.Model(&UserStar{}).Where("`user_id` = ? and `star_id` = ?", userId, starId).Take(&resp).Error; err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case gormc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserStarModel) Update(ctx context.Context, tx *gorm.DB, data *UserStar) error {
	old, err := m.FindOne(ctx, data.Id)
	if err != nil && err != ErrNotFound {
		return err
	}
	err = m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Save(data).Error
	}, m.getCacheKeys(old)...)
	return err
}

func (m *defaultUserStarModel) getCacheKeys(data *UserStar) []string {
	if data == nil {
		return []string{}
	}
	userStarIdKey := fmt.Sprintf("%s%v", cacheUserStarIdPrefix, data.Id)
	userStarUserIdStarIdKey := fmt.Sprintf("%s%v:%v", cacheUserStarUserIdStarIdPrefix, data.UserId, data.StarId)
	cacheKeys := []string{
		userStarIdKey, userStarUserIdStarIdKey,
	}
	cacheKeys = append(cacheKeys, m.customCacheKeys(data)...)
	return cacheKeys
}

func (m *defaultUserStarModel) Delete(ctx context.Context, tx *gorm.DB, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		if err == ErrNotFound {
			return nil
		}
		return err
	}
	err = m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Delete(&UserStar{}, id).Error
	}, m.getCacheKeys(data)...)
	return err
}

func (m *defaultUserStarModel) Transaction(ctx context.Context, fn func(db *gorm.DB) error) error {
	return m.TransactCtx(ctx, fn)
}

func (m *defaultUserStarModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheUserStarIdPrefix, primary)
}

func (m *defaultUserStarModel) queryPrimary(conn *gorm.DB, v, primary interface{}) error {
	return conn.Model(&UserStar{}).Where("`id` = ?", primary).Take(v).Error
}
