// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.22.2
// source: postcenter.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PostCenter_SendPost_FullMethodName       = "/pb.PostCenter/sendPost"
	PostCenter_GetPostDetail_FullMethodName  = "/pb.PostCenter/getPostDetail"
	PostCenter_GetSomeonePost_FullMethodName = "/pb.PostCenter/getSomeonePost"
	PostCenter_DeletePost_FullMethodName     = "/pb.PostCenter/deletePost"
	PostCenter_CommentPost_FullMethodName    = "/pb.PostCenter/commentPost"
	PostCenter_ViewPost_FullMethodName       = "/pb.PostCenter/viewPost"
	PostCenter_LikePost_FullMethodName       = "/pb.PostCenter/likePost"
	PostCenter_CancelLike_FullMethodName     = "/pb.PostCenter/cancelLike"
	PostCenter_IfLike_FullMethodName         = "/pb.PostCenter/ifLike"
)

// PostCenterClient is the client API for PostCenter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PostCenterClient interface {
	SendPost(ctx context.Context, in *PostRequest, opts ...grpc.CallOption) (*PostResponse, error)
	GetPostDetail(ctx context.Context, in *GetPostDetailRequest, opts ...grpc.CallOption) (*GetPostDetailResponse, error)
	GetSomeonePost(ctx context.Context, in *GetSomeonePostRequest, opts ...grpc.CallOption) (*GetSomeonePostResponse, error)
	DeletePost(ctx context.Context, in *DeletePostRequest, opts ...grpc.CallOption) (*DeletePostResponse, error)
	CommentPost(ctx context.Context, in *CommentPostRequest, opts ...grpc.CallOption) (*CommentPostResponse, error)
	ViewPost(ctx context.Context, in *ViewPostRequest, opts ...grpc.CallOption) (*ViewPostResponse, error)
	LikePost(ctx context.Context, in *LikePostRequest, opts ...grpc.CallOption) (*LikePostResponse, error)
	CancelLike(ctx context.Context, in *CancelRequest, opts ...grpc.CallOption) (*CancelResponse, error)
	IfLike(ctx context.Context, in *IfLikeRequest, opts ...grpc.CallOption) (*IfLikeResponse, error)
}

type postCenterClient struct {
	cc grpc.ClientConnInterface
}

func NewPostCenterClient(cc grpc.ClientConnInterface) PostCenterClient {
	return &postCenterClient{cc}
}

func (c *postCenterClient) SendPost(ctx context.Context, in *PostRequest, opts ...grpc.CallOption) (*PostResponse, error) {
	out := new(PostResponse)
	err := c.cc.Invoke(ctx, PostCenter_SendPost_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postCenterClient) GetPostDetail(ctx context.Context, in *GetPostDetailRequest, opts ...grpc.CallOption) (*GetPostDetailResponse, error) {
	out := new(GetPostDetailResponse)
	err := c.cc.Invoke(ctx, PostCenter_GetPostDetail_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postCenterClient) GetSomeonePost(ctx context.Context, in *GetSomeonePostRequest, opts ...grpc.CallOption) (*GetSomeonePostResponse, error) {
	out := new(GetSomeonePostResponse)
	err := c.cc.Invoke(ctx, PostCenter_GetSomeonePost_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postCenterClient) DeletePost(ctx context.Context, in *DeletePostRequest, opts ...grpc.CallOption) (*DeletePostResponse, error) {
	out := new(DeletePostResponse)
	err := c.cc.Invoke(ctx, PostCenter_DeletePost_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postCenterClient) CommentPost(ctx context.Context, in *CommentPostRequest, opts ...grpc.CallOption) (*CommentPostResponse, error) {
	out := new(CommentPostResponse)
	err := c.cc.Invoke(ctx, PostCenter_CommentPost_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postCenterClient) ViewPost(ctx context.Context, in *ViewPostRequest, opts ...grpc.CallOption) (*ViewPostResponse, error) {
	out := new(ViewPostResponse)
	err := c.cc.Invoke(ctx, PostCenter_ViewPost_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postCenterClient) LikePost(ctx context.Context, in *LikePostRequest, opts ...grpc.CallOption) (*LikePostResponse, error) {
	out := new(LikePostResponse)
	err := c.cc.Invoke(ctx, PostCenter_LikePost_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postCenterClient) CancelLike(ctx context.Context, in *CancelRequest, opts ...grpc.CallOption) (*CancelResponse, error) {
	out := new(CancelResponse)
	err := c.cc.Invoke(ctx, PostCenter_CancelLike_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postCenterClient) IfLike(ctx context.Context, in *IfLikeRequest, opts ...grpc.CallOption) (*IfLikeResponse, error) {
	out := new(IfLikeResponse)
	err := c.cc.Invoke(ctx, PostCenter_IfLike_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostCenterServer is the server API for PostCenter service.
// All implementations must embed UnimplementedPostCenterServer
// for forward compatibility
type PostCenterServer interface {
	SendPost(context.Context, *PostRequest) (*PostResponse, error)
	GetPostDetail(context.Context, *GetPostDetailRequest) (*GetPostDetailResponse, error)
	GetSomeonePost(context.Context, *GetSomeonePostRequest) (*GetSomeonePostResponse, error)
	DeletePost(context.Context, *DeletePostRequest) (*DeletePostResponse, error)
	CommentPost(context.Context, *CommentPostRequest) (*CommentPostResponse, error)
	ViewPost(context.Context, *ViewPostRequest) (*ViewPostResponse, error)
	LikePost(context.Context, *LikePostRequest) (*LikePostResponse, error)
	CancelLike(context.Context, *CancelRequest) (*CancelResponse, error)
	IfLike(context.Context, *IfLikeRequest) (*IfLikeResponse, error)
	mustEmbedUnimplementedPostCenterServer()
}

// UnimplementedPostCenterServer must be embedded to have forward compatible implementations.
type UnimplementedPostCenterServer struct {
}

func (UnimplementedPostCenterServer) SendPost(context.Context, *PostRequest) (*PostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendPost not implemented")
}
func (UnimplementedPostCenterServer) GetPostDetail(context.Context, *GetPostDetailRequest) (*GetPostDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPostDetail not implemented")
}
func (UnimplementedPostCenterServer) GetSomeonePost(context.Context, *GetSomeonePostRequest) (*GetSomeonePostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSomeonePost not implemented")
}
func (UnimplementedPostCenterServer) DeletePost(context.Context, *DeletePostRequest) (*DeletePostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePost not implemented")
}
func (UnimplementedPostCenterServer) CommentPost(context.Context, *CommentPostRequest) (*CommentPostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommentPost not implemented")
}
func (UnimplementedPostCenterServer) ViewPost(context.Context, *ViewPostRequest) (*ViewPostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ViewPost not implemented")
}
func (UnimplementedPostCenterServer) LikePost(context.Context, *LikePostRequest) (*LikePostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LikePost not implemented")
}
func (UnimplementedPostCenterServer) CancelLike(context.Context, *CancelRequest) (*CancelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelLike not implemented")
}
func (UnimplementedPostCenterServer) IfLike(context.Context, *IfLikeRequest) (*IfLikeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IfLike not implemented")
}
func (UnimplementedPostCenterServer) mustEmbedUnimplementedPostCenterServer() {}

// UnsafePostCenterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PostCenterServer will
// result in compilation errors.
type UnsafePostCenterServer interface {
	mustEmbedUnimplementedPostCenterServer()
}

func RegisterPostCenterServer(s grpc.ServiceRegistrar, srv PostCenterServer) {
	s.RegisterService(&PostCenter_ServiceDesc, srv)
}

func _PostCenter_SendPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostCenterServer).SendPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostCenter_SendPost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostCenterServer).SendPost(ctx, req.(*PostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostCenter_GetPostDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostCenterServer).GetPostDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostCenter_GetPostDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostCenterServer).GetPostDetail(ctx, req.(*GetPostDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostCenter_GetSomeonePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSomeonePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostCenterServer).GetSomeonePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostCenter_GetSomeonePost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostCenterServer).GetSomeonePost(ctx, req.(*GetSomeonePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostCenter_DeletePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostCenterServer).DeletePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostCenter_DeletePost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostCenterServer).DeletePost(ctx, req.(*DeletePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostCenter_CommentPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommentPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostCenterServer).CommentPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostCenter_CommentPost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostCenterServer).CommentPost(ctx, req.(*CommentPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostCenter_ViewPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ViewPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostCenterServer).ViewPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostCenter_ViewPost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostCenterServer).ViewPost(ctx, req.(*ViewPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostCenter_LikePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LikePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostCenterServer).LikePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostCenter_LikePost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostCenterServer).LikePost(ctx, req.(*LikePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostCenter_CancelLike_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostCenterServer).CancelLike(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostCenter_CancelLike_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostCenterServer).CancelLike(ctx, req.(*CancelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostCenter_IfLike_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IfLikeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostCenterServer).IfLike(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostCenter_IfLike_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostCenterServer).IfLike(ctx, req.(*IfLikeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PostCenter_ServiceDesc is the grpc.ServiceDesc for PostCenter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PostCenter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.PostCenter",
	HandlerType: (*PostCenterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "sendPost",
			Handler:    _PostCenter_SendPost_Handler,
		},
		{
			MethodName: "getPostDetail",
			Handler:    _PostCenter_GetPostDetail_Handler,
		},
		{
			MethodName: "getSomeonePost",
			Handler:    _PostCenter_GetSomeonePost_Handler,
		},
		{
			MethodName: "deletePost",
			Handler:    _PostCenter_DeletePost_Handler,
		},
		{
			MethodName: "commentPost",
			Handler:    _PostCenter_CommentPost_Handler,
		},
		{
			MethodName: "viewPost",
			Handler:    _PostCenter_ViewPost_Handler,
		},
		{
			MethodName: "likePost",
			Handler:    _PostCenter_LikePost_Handler,
		},
		{
			MethodName: "cancelLike",
			Handler:    _PostCenter_CancelLike_Handler,
		},
		{
			MethodName: "ifLike",
			Handler:    _PostCenter_IfLike_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "postcenter.proto",
}
