// Code generated by goctl. DO NOT EDIT.
package types

type Image struct {
	Id    int64  `json:"id"`
	Type  string `json:"type"`
	OutId int64  `json:"outId"`
	Url   string `json:"url"`
}

type UploadImageRequest struct {
	Type  string `json:"type"`
	OutId int64  `json:"outId"`
	Url   string `json:"url"`
}

type UploadImageResponse struct {
	Image Image `json:"image"`
}

type GetAllImagesRequest struct {
	Type  string `path:"type"`
	OutId int64  `path:"outId"`
}

type GetAllImagesResponse struct {
	Images []Image `json:"image"`
}

type GetImageDetailRequest struct {
	Id int64 `path:"id"`
}

type GetImageDetailResponse struct {
	Image Image `json:"image"`
}

type DeleteImageRequest struct {
	Id int64 `path:"id"`
}

type DeleteImageReponse struct {
	Id int64 `json:"id"`
}
