// Code generated by goctl. DO NOT EDIT.
// Source: usercenter.proto

package usercenter

import (
	"context"

	"LingXi/app/usercenter/cmd/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AuthReq           = pb.AuthReq
	AuthResp          = pb.AuthResp
	GenerateTokenReq  = pb.GenerateTokenReq
	GenerateTokenResp = pb.GenerateTokenResp
	LoginReq          = pb.LoginReq
	LoginResp         = pb.LoginResp
	RegisterReq       = pb.RegisterReq
	RegisterResp      = pb.RegisterResp
	UpdateInfoReq     = pb.UpdateInfoReq
	UpdateInfoResp    = pb.UpdateInfoResp
	UpdatePSWReq      = pb.UpdatePSWReq
	UpdatePSWResp     = pb.UpdatePSWResp
	User              = pb.User
	UserAuth          = pb.UserAuth
	UserInfoReq       = pb.UserInfoReq
	UserInfoResp      = pb.UserInfoResp
	VerificationReq   = pb.VerificationReq
	VerificationResp  = pb.VerificationResp

	UserCenter interface {
		Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
		Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error)
		GetVerification(ctx context.Context, in *VerificationReq, opts ...grpc.CallOption) (*VerificationResp, error)
		GetUserInfo(ctx context.Context, in *UserInfoReq, opts ...grpc.CallOption) (*UserInfoResp, error)
		GenerateToken(ctx context.Context, in *GenerateTokenReq, opts ...grpc.CallOption) (*GenerateTokenResp, error)
		UpdateInfo(ctx context.Context, in *UpdateInfoReq, opts ...grpc.CallOption) (*UpdateInfoResp, error)
		UpdatePSW(ctx context.Context, in *UpdatePSWReq, opts ...grpc.CallOption) (*UpdatePSWResp, error)
		GiveUserAuth(ctx context.Context, in *AuthReq, opts ...grpc.CallOption) (*AuthResp, error)
	}

	defaultUserCenter struct {
		cli zrpc.Client
	}
)

func NewUserCenter(cli zrpc.Client) UserCenter {
	return &defaultUserCenter{
		cli: cli,
	}
}

func (m *defaultUserCenter) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	client := pb.NewUserCenterClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

func (m *defaultUserCenter) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error) {
	client := pb.NewUserCenterClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}

func (m *defaultUserCenter) GetVerification(ctx context.Context, in *VerificationReq, opts ...grpc.CallOption) (*VerificationResp, error) {
	client := pb.NewUserCenterClient(m.cli.Conn())
	return client.GetVerification(ctx, in, opts...)
}

func (m *defaultUserCenter) GetUserInfo(ctx context.Context, in *UserInfoReq, opts ...grpc.CallOption) (*UserInfoResp, error) {
	client := pb.NewUserCenterClient(m.cli.Conn())
	return client.GetUserInfo(ctx, in, opts...)
}

func (m *defaultUserCenter) GenerateToken(ctx context.Context, in *GenerateTokenReq, opts ...grpc.CallOption) (*GenerateTokenResp, error) {
	client := pb.NewUserCenterClient(m.cli.Conn())
	return client.GenerateToken(ctx, in, opts...)
}

func (m *defaultUserCenter) UpdateInfo(ctx context.Context, in *UpdateInfoReq, opts ...grpc.CallOption) (*UpdateInfoResp, error) {
	client := pb.NewUserCenterClient(m.cli.Conn())
	return client.UpdateInfo(ctx, in, opts...)
}

func (m *defaultUserCenter) UpdatePSW(ctx context.Context, in *UpdatePSWReq, opts ...grpc.CallOption) (*UpdatePSWResp, error) {
	client := pb.NewUserCenterClient(m.cli.Conn())
	return client.UpdatePSW(ctx, in, opts...)
}

func (m *defaultUserCenter) GiveUserAuth(ctx context.Context, in *AuthReq, opts ...grpc.CallOption) (*AuthResp, error) {
	client := pb.NewUserCenterClient(m.cli.Conn())
	return client.GiveUserAuth(ctx, in, opts...)
}
