// Code generated by goctl. DO NOT EDIT.
// Source: chat.proto

package server

import (
	"context"

	"LingXi/app/chat/cmd/rpc/internal/logic"
	"LingXi/app/chat/cmd/rpc/internal/svc"
	"LingXi/app/chat/cmd/rpc/pb"
)

type ChatcenterServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedChatcenterServer
}

func NewChatcenterServer(svcCtx *svc.ServiceContext) *ChatcenterServer {
	return &ChatcenterServer{
		svcCtx: svcCtx,
	}
}

func (s *ChatcenterServer) GetMessage(ctx context.Context, in *pb.GetMessageRequest) (*pb.GetMessageResponse, error) {
	l := logic.NewGetMessageLogic(ctx, s.svcCtx)
	return l.GetMessage(in)
}

func (s *ChatcenterServer) SaveMessageRequest(ctx context.Context, in *pb.SaveMessageRequest) (*pb.SaveMessageResponse, error) {
	l := logic.NewSaveMessageRequestLogic(ctx, s.svcCtx)
	return l.SaveMessageRequest(in)
}

func (s *ChatcenterServer) GetLastMessage(ctx context.Context, in *pb.LastMessageRequest) (*pb.LastMessageResponse, error) {
	l := logic.NewGetLastMessageLogic(ctx, s.svcCtx)
	return l.GetLastMessage(in)
}
