// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.22.2
// source: tweetcenter.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	TweetCenter_PostTweet_FullMethodName = "/pb.TweetCenter/postTweet"
)

// TweetCenterClient is the client API for TweetCenter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TweetCenterClient interface {
	PostTweet(ctx context.Context, in *TweetRequest, opts ...grpc.CallOption) (*TweetResponse, error)
}

type tweetCenterClient struct {
	cc grpc.ClientConnInterface
}

func NewTweetCenterClient(cc grpc.ClientConnInterface) TweetCenterClient {
	return &tweetCenterClient{cc}
}

func (c *tweetCenterClient) PostTweet(ctx context.Context, in *TweetRequest, opts ...grpc.CallOption) (*TweetResponse, error) {
	out := new(TweetResponse)
	err := c.cc.Invoke(ctx, TweetCenter_PostTweet_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TweetCenterServer is the server API for TweetCenter service.
// All implementations must embed UnimplementedTweetCenterServer
// for forward compatibility
type TweetCenterServer interface {
	PostTweet(context.Context, *TweetRequest) (*TweetResponse, error)
	mustEmbedUnimplementedTweetCenterServer()
}

// UnimplementedTweetCenterServer must be embedded to have forward compatible implementations.
type UnimplementedTweetCenterServer struct {
}

func (UnimplementedTweetCenterServer) PostTweet(context.Context, *TweetRequest) (*TweetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostTweet not implemented")
}
func (UnimplementedTweetCenterServer) mustEmbedUnimplementedTweetCenterServer() {}

// UnsafeTweetCenterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TweetCenterServer will
// result in compilation errors.
type UnsafeTweetCenterServer interface {
	mustEmbedUnimplementedTweetCenterServer()
}

func RegisterTweetCenterServer(s grpc.ServiceRegistrar, srv TweetCenterServer) {
	s.RegisterService(&TweetCenter_ServiceDesc, srv)
}

func _TweetCenter_PostTweet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TweetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TweetCenterServer).PostTweet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TweetCenter_PostTweet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TweetCenterServer).PostTweet(ctx, req.(*TweetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TweetCenter_ServiceDesc is the grpc.ServiceDesc for TweetCenter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TweetCenter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.TweetCenter",
	HandlerType: (*TweetCenterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "postTweet",
			Handler:    _TweetCenter_PostTweet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tweetcenter.proto",
}
