// Code generated by goctl. DO NOT EDIT.
// Source: connectioncenter.proto

package server

import (
	"context"

	"LingXi/app/connection/cmd/rpc/internal/logic"
	"LingXi/app/connection/cmd/rpc/internal/svc"
	"LingXi/app/connection/cmd/rpc/pb"
)

type ConnectioncenterServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedConnectioncenterServer
}

func NewConnectioncenterServer(svcCtx *svc.ServiceContext) *ConnectioncenterServer {
	return &ConnectioncenterServer{
		svcCtx: svcCtx,
	}
}

func (s *ConnectioncenterServer) AddConnection(ctx context.Context, in *pb.AddConnectionRequest) (*pb.AddConnectionResponse, error) {
	l := logic.NewAddConnectionLogic(ctx, s.svcCtx)
	return l.AddConnection(in)
}

func (s *ConnectioncenterServer) CheckConnection(ctx context.Context, in *pb.CheckConnectionRequest) (*pb.CheckConnectionResponse, error) {
	l := logic.NewCheckConnectionLogic(ctx, s.svcCtx)
	return l.CheckConnection(in)
}
