// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	image "LingXi/app/images/cmd/api/internal/handler/image"
	"LingXi/app/images/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/image",
				Handler: image.UploadImageHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/image/:type/:outId",
				Handler: image.GetAllImagesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/image/:id",
				Handler: image.GetImageDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/image/:id",
				Handler: image.DeleteImageHandler(serverCtx),
			},
		},
		rest.WithPrefix("/imagecenter/v1"),
	)
}
