// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	connection "LingXi/app/connection/cmd/api/internal/handler/connection"
	"LingXi/app/connection/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/add",
				Handler: connection.AddConnectionHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/check",
				Handler: connection.CheckConnectionHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/connectioncenter/v1"),
	)
}
