// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"time"

	"github.com/SpectatorNan/gorm-zero/gormc"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"gorm.io/gorm"
)

var (
	cacheImagesIdPrefix = "cache:images:id:"
)

type (
	imagesModel interface {
		Insert(ctx context.Context, tx *gorm.DB, data *Images) error

		FindOne(ctx context.Context, id int64) (*Images, error)
		Update(ctx context.Context, tx *gorm.DB, data *Images) error

		Delete(ctx context.Context, tx *gorm.DB, id int64) error
		Transaction(ctx context.Context, fn func(db *gorm.DB) error) error
	}

	defaultImagesModel struct {
		gormc.CachedConn
		table string
	}

	Images struct {
		Id         int64        `gorm:"column:id"`
		Type       string       `gorm:"column:type"`
		OutId      int64        `gorm:"column:out_id"`
		Url        string       `gorm:"column:url"`
		CreateTime time.Time    `gorm:"column:create_time"`
		UpdateTime time.Time    `gorm:"column:update_time"`
		DeleteTime sql.NullTime `gorm:"column:delete_time"`
	}
)

func (Images) TableName() string {
	return "`images`"
}

func newImagesModel(conn *gorm.DB, c cache.CacheConf) *defaultImagesModel {
	return &defaultImagesModel{
		CachedConn: gormc.NewConn(conn, c),
		table:      "`images`",
	}
}

func (m *defaultImagesModel) Insert(ctx context.Context, tx *gorm.DB, data *Images) error {

	err := m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Save(&data).Error
	}, m.getCacheKeys(data)...)
	return err
}

func (m *defaultImagesModel) FindOne(ctx context.Context, id int64) (*Images, error) {
	imagesIdKey := fmt.Sprintf("%s%v", cacheImagesIdPrefix, id)
	var resp Images
	err := m.QueryCtx(ctx, &resp, imagesIdKey, func(conn *gorm.DB, v interface{}) error {
		return conn.Model(&Images{}).Where("`id` = ?", id).First(&resp).Error
	})
	switch err {
	case nil:
		return &resp, nil
	case gormc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultImagesModel) Update(ctx context.Context, tx *gorm.DB, data *Images) error {
	old, err := m.FindOne(ctx, data.Id)
	if err != nil && err != ErrNotFound {
		return err
	}
	err = m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Save(data).Error
	}, m.getCacheKeys(old)...)
	return err
}

func (m *defaultImagesModel) getCacheKeys(data *Images) []string {
	if data == nil {
		return []string{}
	}
	imagesIdKey := fmt.Sprintf("%s%v", cacheImagesIdPrefix, data.Id)
	cacheKeys := []string{
		imagesIdKey,
	}
	cacheKeys = append(cacheKeys, m.customCacheKeys(data)...)
	return cacheKeys
}

func (m *defaultImagesModel) Delete(ctx context.Context, tx *gorm.DB, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		if err == ErrNotFound {
			return nil
		}
		return err
	}
	err = m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Delete(&Images{}, id).Error
	}, m.getCacheKeys(data)...)
	return err
}

func (m *defaultImagesModel) Transaction(ctx context.Context, fn func(db *gorm.DB) error) error {
	return m.TransactCtx(ctx, fn)
}

func (m *defaultImagesModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheImagesIdPrefix, primary)
}

func (m *defaultImagesModel) queryPrimary(conn *gorm.DB, v, primary interface{}) error {
	return conn.Model(&Images{}).Where("`id` = ?", primary).Take(v).Error
}
