// Code generated by goctl. DO NOT EDIT.
// Source: likecenter.proto

package likecenter

import (
	"context"

	"LingXi/app/like/cmd/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CancelLikeRequest  = pb.CancelLikeRequest
	CancelLikeResponse = pb.CancelLikeResponse
	CheckLikeRequest   = pb.CheckLikeRequest
	CheckLikeResponse  = pb.CheckLikeResponse
	GetLikesRequest    = pb.GetLikesRequest
	GetLikesResponse   = pb.GetLikesResponse
	LikeRequest        = pb.LikeRequest
	LikeResponse       = pb.LikeResponse

	Likecenter interface {
		PostLike(ctx context.Context, in *LikeRequest, opts ...grpc.CallOption) (*LikeResponse, error)
		CheckLike(ctx context.Context, in *CheckLikeRequest, opts ...grpc.CallOption) (*CheckLikeResponse, error)
		CancelLike(ctx context.Context, in *CancelLikeRequest, opts ...grpc.CallOption) (*CancelLikeResponse, error)
		GetLikes(ctx context.Context, in *GetLikesRequest, opts ...grpc.CallOption) (*GetLikesResponse, error)
	}

	defaultLikecenter struct {
		cli zrpc.Client
	}
)

func NewLikecenter(cli zrpc.Client) Likecenter {
	return &defaultLikecenter{
		cli: cli,
	}
}

func (m *defaultLikecenter) PostLike(ctx context.Context, in *LikeRequest, opts ...grpc.CallOption) (*LikeResponse, error) {
	client := pb.NewLikecenterClient(m.cli.Conn())
	return client.PostLike(ctx, in, opts...)
}

func (m *defaultLikecenter) CheckLike(ctx context.Context, in *CheckLikeRequest, opts ...grpc.CallOption) (*CheckLikeResponse, error) {
	client := pb.NewLikecenterClient(m.cli.Conn())
	return client.CheckLike(ctx, in, opts...)
}

func (m *defaultLikecenter) CancelLike(ctx context.Context, in *CancelLikeRequest, opts ...grpc.CallOption) (*CancelLikeResponse, error) {
	client := pb.NewLikecenterClient(m.cli.Conn())
	return client.CancelLike(ctx, in, opts...)
}

func (m *defaultLikecenter) GetLikes(ctx context.Context, in *GetLikesRequest, opts ...grpc.CallOption) (*GetLikesResponse, error) {
	client := pb.NewLikecenterClient(m.cli.Conn())
	return client.GetLikes(ctx, in, opts...)
}
