// Code generated by goctl. DO NOT EDIT.
// Source: chat.proto

package chatcenter

import (
	"context"

	"LingXi/app/chat/cmd/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetMessageRequest   = pb.GetMessageRequest
	GetMessageResponse  = pb.GetMessageResponse
	LastMessageRequest  = pb.LastMessageRequest
	LastMessageResponse = pb.LastMessageResponse
	Message             = pb.Message
	SaveMessageRequest  = pb.SaveMessageRequest
	SaveMessageResponse = pb.SaveMessageResponse

	Chatcenter interface {
		GetMessage(ctx context.Context, in *GetMessageRequest, opts ...grpc.CallOption) (*GetMessageResponse, error)
		SaveMessageRequest(ctx context.Context, in *SaveMessageRequest, opts ...grpc.CallOption) (*SaveMessageResponse, error)
		GetLastMessage(ctx context.Context, in *LastMessageRequest, opts ...grpc.CallOption) (*LastMessageResponse, error)
	}

	defaultChatcenter struct {
		cli zrpc.Client
	}
)

func NewChatcenter(cli zrpc.Client) Chatcenter {
	return &defaultChatcenter{
		cli: cli,
	}
}

func (m *defaultChatcenter) GetMessage(ctx context.Context, in *GetMessageRequest, opts ...grpc.CallOption) (*GetMessageResponse, error) {
	client := pb.NewChatcenterClient(m.cli.Conn())
	return client.GetMessage(ctx, in, opts...)
}

func (m *defaultChatcenter) SaveMessageRequest(ctx context.Context, in *SaveMessageRequest, opts ...grpc.CallOption) (*SaveMessageResponse, error) {
	client := pb.NewChatcenterClient(m.cli.Conn())
	return client.SaveMessageRequest(ctx, in, opts...)
}

func (m *defaultChatcenter) GetLastMessage(ctx context.Context, in *LastMessageRequest, opts ...grpc.CallOption) (*LastMessageResponse, error) {
	client := pb.NewChatcenterClient(m.cli.Conn())
	return client.GetLastMessage(ctx, in, opts...)
}
