// Code generated by goctl. DO NOT EDIT.
// Source: postcenter.proto

package postcenter

import (
	"context"

	"LingXi/app/post/cmd/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CancelRequest          = pb.CancelRequest
	CancelResponse         = pb.CancelResponse
	CommentPostRequest     = pb.CommentPostRequest
	CommentPostResponse    = pb.CommentPostResponse
	DeletePostRequest      = pb.DeletePostRequest
	DeletePostResponse     = pb.DeletePostResponse
	GetPostDetailRequest   = pb.GetPostDetailRequest
	GetPostDetailResponse  = pb.GetPostDetailResponse
	GetSomeonePostRequest  = pb.GetSomeonePostRequest
	GetSomeonePostResponse = pb.GetSomeonePostResponse
	IfLikeRequest          = pb.IfLikeRequest
	IfLikeResponse         = pb.IfLikeResponse
	LikePostRequest        = pb.LikePostRequest
	LikePostResponse       = pb.LikePostResponse
	Post                   = pb.Post
	PostRequest            = pb.PostRequest
	PostResponse           = pb.PostResponse
	ViewPostRequest        = pb.ViewPostRequest
	ViewPostResponse       = pb.ViewPostResponse

	PostCenter interface {
		SendPost(ctx context.Context, in *PostRequest, opts ...grpc.CallOption) (*PostResponse, error)
		GetPostDetail(ctx context.Context, in *GetPostDetailRequest, opts ...grpc.CallOption) (*GetPostDetailResponse, error)
		GetSomeonePost(ctx context.Context, in *GetSomeonePostRequest, opts ...grpc.CallOption) (*GetSomeonePostResponse, error)
		DeletePost(ctx context.Context, in *DeletePostRequest, opts ...grpc.CallOption) (*DeletePostResponse, error)
		CommentPost(ctx context.Context, in *CommentPostRequest, opts ...grpc.CallOption) (*CommentPostResponse, error)
		ViewPost(ctx context.Context, in *ViewPostRequest, opts ...grpc.CallOption) (*ViewPostResponse, error)
		LikePost(ctx context.Context, in *LikePostRequest, opts ...grpc.CallOption) (*LikePostResponse, error)
		CancelLike(ctx context.Context, in *CancelRequest, opts ...grpc.CallOption) (*CancelResponse, error)
		IfLike(ctx context.Context, in *IfLikeRequest, opts ...grpc.CallOption) (*IfLikeResponse, error)
	}

	defaultPostCenter struct {
		cli zrpc.Client
	}
)

func NewPostCenter(cli zrpc.Client) PostCenter {
	return &defaultPostCenter{
		cli: cli,
	}
}

func (m *defaultPostCenter) SendPost(ctx context.Context, in *PostRequest, opts ...grpc.CallOption) (*PostResponse, error) {
	client := pb.NewPostCenterClient(m.cli.Conn())
	return client.SendPost(ctx, in, opts...)
}

func (m *defaultPostCenter) GetPostDetail(ctx context.Context, in *GetPostDetailRequest, opts ...grpc.CallOption) (*GetPostDetailResponse, error) {
	client := pb.NewPostCenterClient(m.cli.Conn())
	return client.GetPostDetail(ctx, in, opts...)
}

func (m *defaultPostCenter) GetSomeonePost(ctx context.Context, in *GetSomeonePostRequest, opts ...grpc.CallOption) (*GetSomeonePostResponse, error) {
	client := pb.NewPostCenterClient(m.cli.Conn())
	return client.GetSomeonePost(ctx, in, opts...)
}

func (m *defaultPostCenter) DeletePost(ctx context.Context, in *DeletePostRequest, opts ...grpc.CallOption) (*DeletePostResponse, error) {
	client := pb.NewPostCenterClient(m.cli.Conn())
	return client.DeletePost(ctx, in, opts...)
}

func (m *defaultPostCenter) CommentPost(ctx context.Context, in *CommentPostRequest, opts ...grpc.CallOption) (*CommentPostResponse, error) {
	client := pb.NewPostCenterClient(m.cli.Conn())
	return client.CommentPost(ctx, in, opts...)
}

func (m *defaultPostCenter) ViewPost(ctx context.Context, in *ViewPostRequest, opts ...grpc.CallOption) (*ViewPostResponse, error) {
	client := pb.NewPostCenterClient(m.cli.Conn())
	return client.ViewPost(ctx, in, opts...)
}

func (m *defaultPostCenter) LikePost(ctx context.Context, in *LikePostRequest, opts ...grpc.CallOption) (*LikePostResponse, error) {
	client := pb.NewPostCenterClient(m.cli.Conn())
	return client.LikePost(ctx, in, opts...)
}

func (m *defaultPostCenter) CancelLike(ctx context.Context, in *CancelRequest, opts ...grpc.CallOption) (*CancelResponse, error) {
	client := pb.NewPostCenterClient(m.cli.Conn())
	return client.CancelLike(ctx, in, opts...)
}

func (m *defaultPostCenter) IfLike(ctx context.Context, in *IfLikeRequest, opts ...grpc.CallOption) (*IfLikeResponse, error) {
	client := pb.NewPostCenterClient(m.cli.Conn())
	return client.IfLike(ctx, in, opts...)
}
