// Code generated by goctl. DO NOT EDIT.
// Source: imagecenter.proto

package server

import (
	"context"

	"LingXi/app/images/cmd/rpc/internal/logic"
	"LingXi/app/images/cmd/rpc/internal/svc"
	"LingXi/app/images/cmd/rpc/pb"
)

type ImageCenterServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedImageCenterServer
}

func NewImageCenterServer(svcCtx *svc.ServiceContext) *ImageCenterServer {
	return &ImageCenterServer{
		svcCtx: svcCtx,
	}
}

func (s *ImageCenterServer) PostImage(ctx context.Context, in *pb.PostImageRequest) (*pb.PostImageResponse, error) {
	l := logic.NewPostImageLogic(ctx, s.svcCtx)
	return l.PostImage(in)
}

func (s *ImageCenterServer) GetAllImages(ctx context.Context, in *pb.GetAllImagesRequest) (*pb.GetAllImagesResponse, error) {
	l := logic.NewGetAllImagesLogic(ctx, s.svcCtx)
	return l.GetAllImages(in)
}

func (s *ImageCenterServer) GetDetail(ctx context.Context, in *pb.GetDetailRequest) (*pb.GetDetailResponse, error) {
	l := logic.NewGetDetailLogic(ctx, s.svcCtx)
	return l.GetDetail(in)
}

func (s *ImageCenterServer) DeleteImage(ctx context.Context, in *pb.DeleteImageRequest) (*pb.DeleteImageResponse, error) {
	l := logic.NewDeleteImageLogic(ctx, s.svcCtx)
	return l.DeleteImage(in)
}

func (s *ImageCenterServer) GetOneImage(ctx context.Context, in *pb.GetOneImageRequest) (*pb.GetOneImageResponse, error) {
	l := logic.NewGetOneImageLogic(ctx, s.svcCtx)
	return l.GetOneImage(in)
}
