// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"fmt"
	"time"

	"github.com/SpectatorNan/gorm-zero/gormc"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"gorm.io/gorm"
)

var (
	cacheCommentsIdPrefix = "cache:comments:id:"
)

type (
	commentsModel interface {
		Insert(ctx context.Context, tx *gorm.DB, data *Comments) error

		FindOne(ctx context.Context, id int64) (*Comments, error)
		Update(ctx context.Context, tx *gorm.DB, data *Comments) error

		Delete(ctx context.Context, tx *gorm.DB, id int64) error
		Transaction(ctx context.Context, fn func(db *gorm.DB) error) error
	}

	defaultCommentsModel struct {
		gormc.CachedConn
		table string
	}

	Comments struct {
		Id          int64     `gorm:"column:id"`
		PublisherId int64     `gorm:"column:publisher_id"`
		Type        string    `gorm:"column:type"`
		Content     string    `gorm:"column:content"`
		LikeNum     int64     `gorm:"column:like_num"`
		ReplyNum    int64     `gorm:"column:reply_num"`
		CreateTime  time.Time `gorm:"column:create_time"`
		OutId       int64     `gorm:"column:out_id"`
	}
)

func (Comments) TableName() string {
	return "`comments`"
}

func newCommentsModel(conn *gorm.DB, c cache.CacheConf) *defaultCommentsModel {
	return &defaultCommentsModel{
		CachedConn: gormc.NewConn(conn, c),
		table:      "`comments`",
	}
}

func (m *defaultCommentsModel) Insert(ctx context.Context, tx *gorm.DB, data *Comments) error {

	err := m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Save(&data).Error
	}, m.getCacheKeys(data)...)
	return err
}

func (m *defaultCommentsModel) FindOne(ctx context.Context, id int64) (*Comments, error) {
	commentsIdKey := fmt.Sprintf("%s%v", cacheCommentsIdPrefix, id)
	var resp Comments
	err := m.QueryCtx(ctx, &resp, commentsIdKey, func(conn *gorm.DB, v interface{}) error {
		return conn.Model(&Comments{}).Where("`id` = ?", id).First(&resp).Error
	})
	switch err {
	case nil:
		return &resp, nil
	case gormc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCommentsModel) Update(ctx context.Context, tx *gorm.DB, data *Comments) error {
	old, err := m.FindOne(ctx, data.Id)
	if err != nil && err != ErrNotFound {
		return err
	}
	err = m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Save(data).Error
	}, m.getCacheKeys(old)...)
	return err
}

func (m *defaultCommentsModel) getCacheKeys(data *Comments) []string {
	if data == nil {
		return []string{}
	}
	commentsIdKey := fmt.Sprintf("%s%v", cacheCommentsIdPrefix, data.Id)
	cacheKeys := []string{
		commentsIdKey,
	}
	cacheKeys = append(cacheKeys, m.customCacheKeys(data)...)
	return cacheKeys
}

func (m *defaultCommentsModel) Delete(ctx context.Context, tx *gorm.DB, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		if err == ErrNotFound {
			return nil
		}
		return err
	}
	err = m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Delete(&Comments{}, id).Error
	}, m.getCacheKeys(data)...)
	return err
}

func (m *defaultCommentsModel) Transaction(ctx context.Context, fn func(db *gorm.DB) error) error {
	return m.TransactCtx(ctx, fn)
}

func (m *defaultCommentsModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheCommentsIdPrefix, primary)
}

func (m *defaultCommentsModel) queryPrimary(conn *gorm.DB, v, primary interface{}) error {
	return conn.Model(&Comments{}).Where("`id` = ?", primary).Take(v).Error
}
