// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	stars "LingXi/app/star/cmd/api/internal/handler/stars"
	"LingXi/app/star/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/star",
				Handler: stars.EnterStarHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/star",
				Handler: stars.GetMyStarHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/star/:starId",
				Handler: stars.GetStarDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/star/enter/:starId",
				Handler: stars.IfEnterStarHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/starcenter/v1"),
	)
}
