// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"time"

	"github.com/SpectatorNan/gorm-zero/gormc"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"gorm.io/gorm"
)

var (
	cacheLikeIdPrefix              = "cache:like:id:"
	cacheLikeUserIdTypeOutIdPrefix = "cache:like:userId:type:outId:"
)

type (
	likeModel interface {
		Insert(ctx context.Context, tx *gorm.DB, data *Like) error

		FindOne(ctx context.Context, id int64) (*Like, error)
		FindOneByUserIdTypeOutId(ctx context.Context, userId int64, tp string, outId int64) (*Like, error)
		Update(ctx context.Context, tx *gorm.DB, data *Like) error

		Delete(ctx context.Context, tx *gorm.DB, id int64) error
		Transaction(ctx context.Context, fn func(db *gorm.DB) error) error
	}

	defaultLikeModel struct {
		gormc.CachedConn
		table string
	}

	Like struct {
		Id         int64        `gorm:"column:id"`
		UserId     int64        `gorm:"column:user_id"`
		Type       string       `gorm:"column:type"`
		OutId      int64        `gorm:"column:out_id"`
		CreateTime time.Time    `gorm:"column:create_time"`
		UpdateTime time.Time    `gorm:"column:update_time"`
		DeleteTime sql.NullTime `gorm:"column:delete_time"`
	}
)

func (Like) TableName() string {
	return "`like`"
}

func newLikeModel(conn *gorm.DB, c cache.CacheConf) *defaultLikeModel {
	return &defaultLikeModel{
		CachedConn: gormc.NewConn(conn, c),
		table:      "`like`",
	}
}

func (m *defaultLikeModel) Insert(ctx context.Context, tx *gorm.DB, data *Like) error {

	err := m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Save(&data).Error
	}, m.getCacheKeys(data)...)
	return err
}

func (m *defaultLikeModel) FindOne(ctx context.Context, id int64) (*Like, error) {
	likeIdKey := fmt.Sprintf("%s%v", cacheLikeIdPrefix, id)
	var resp Like
	err := m.QueryCtx(ctx, &resp, likeIdKey, func(conn *gorm.DB, v interface{}) error {
		return conn.Model(&Like{}).Where("`id` = ?", id).First(&resp).Error
	})
	switch err {
	case nil:
		return &resp, nil
	case gormc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLikeModel) FindOneByUserIdTypeOutId(ctx context.Context, userId int64, tp string, outId int64) (*Like, error) {
	likeUserIdTypeOutIdKey := fmt.Sprintf("%s%v:%v:%v", cacheLikeUserIdTypeOutIdPrefix, userId, tp, outId)
	var resp Like
	err := m.QueryRowIndexCtx(ctx, &resp, likeUserIdTypeOutIdKey, m.formatPrimary, func(conn *gorm.DB, v interface{}) (interface{}, error) {
		if err := conn.Model(&Like{}).Where("`user_id` = ? and `type` = ? and `out_id` = ?", userId, tp, outId).Take(&resp).Error; err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case gormc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLikeModel) Update(ctx context.Context, tx *gorm.DB, data *Like) error {
	old, err := m.FindOne(ctx, data.Id)
	if err != nil && err != ErrNotFound {
		return err
	}
	err = m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Save(data).Error
	}, m.getCacheKeys(old)...)
	return err
}

func (m *defaultLikeModel) getCacheKeys(data *Like) []string {
	if data == nil {
		return []string{}
	}
	likeIdKey := fmt.Sprintf("%s%v", cacheLikeIdPrefix, data.Id)
	likeUserIdTypeOutIdKey := fmt.Sprintf("%s%v:%v:%v", cacheLikeUserIdTypeOutIdPrefix, data.UserId, data.Type, data.OutId)
	cacheKeys := []string{
		likeIdKey, likeUserIdTypeOutIdKey,
	}
	cacheKeys = append(cacheKeys, m.customCacheKeys(data)...)
	return cacheKeys
}

func (m *defaultLikeModel) Delete(ctx context.Context, tx *gorm.DB, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		if err == ErrNotFound {
			return nil
		}
		return err
	}
	err = m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Delete(&Like{}, id).Error
	}, m.getCacheKeys(data)...)
	return err
}

func (m *defaultLikeModel) Transaction(ctx context.Context, fn func(db *gorm.DB) error) error {
	return m.TransactCtx(ctx, fn)
}

func (m *defaultLikeModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheLikeIdPrefix, primary)
}

func (m *defaultLikeModel) queryPrimary(conn *gorm.DB, v, primary interface{}) error {
	return conn.Model(&Like{}).Where("`id` = ?", primary).Take(v).Error
}
