// Code generated by goctl. DO NOT EDIT.
// Source: postcenter.proto

package server

import (
	"context"

	"LingXi/app/post/cmd/rpc/internal/logic"
	"LingXi/app/post/cmd/rpc/internal/svc"
	"LingXi/app/post/cmd/rpc/pb"
)

type PostCenterServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedPostCenterServer
}

func NewPostCenterServer(svcCtx *svc.ServiceContext) *PostCenterServer {
	return &PostCenterServer{
		svcCtx: svcCtx,
	}
}

func (s *PostCenterServer) SendPost(ctx context.Context, in *pb.PostRequest) (*pb.PostResponse, error) {
	l := logic.NewSendPostLogic(ctx, s.svcCtx)
	return l.SendPost(in)
}

func (s *PostCenterServer) GetPostDetail(ctx context.Context, in *pb.GetPostDetailRequest) (*pb.GetPostDetailResponse, error) {
	l := logic.NewGetPostDetailLogic(ctx, s.svcCtx)
	return l.GetPostDetail(in)
}

func (s *PostCenterServer) GetSomeonePost(ctx context.Context, in *pb.GetSomeonePostRequest) (*pb.GetSomeonePostResponse, error) {
	l := logic.NewGetSomeonePostLogic(ctx, s.svcCtx)
	return l.GetSomeonePost(in)
}

func (s *PostCenterServer) DeletePost(ctx context.Context, in *pb.DeletePostRequest) (*pb.DeletePostResponse, error) {
	l := logic.NewDeletePostLogic(ctx, s.svcCtx)
	return l.DeletePost(in)
}

func (s *PostCenterServer) CommentPost(ctx context.Context, in *pb.CommentPostRequest) (*pb.CommentPostResponse, error) {
	l := logic.NewCommentPostLogic(ctx, s.svcCtx)
	return l.CommentPost(in)
}

func (s *PostCenterServer) ViewPost(ctx context.Context, in *pb.ViewPostRequest) (*pb.ViewPostResponse, error) {
	l := logic.NewViewPostLogic(ctx, s.svcCtx)
	return l.ViewPost(in)
}

func (s *PostCenterServer) LikePost(ctx context.Context, in *pb.LikePostRequest) (*pb.LikePostResponse, error) {
	l := logic.NewLikePostLogic(ctx, s.svcCtx)
	return l.LikePost(in)
}

func (s *PostCenterServer) CancelLike(ctx context.Context, in *pb.CancelRequest) (*pb.CancelResponse, error) {
	l := logic.NewCancelLikeLogic(ctx, s.svcCtx)
	return l.CancelLike(in)
}

func (s *PostCenterServer) IfLike(ctx context.Context, in *pb.IfLikeRequest) (*pb.IfLikeResponse, error) {
	l := logic.NewIfLikeLogic(ctx, s.svcCtx)
	return l.IfLike(in)
}
