// Code generated by goctl. DO NOT EDIT.
package types

type Message struct {
	Id         int64  `json:"id"`
	ReceiverId int64  `json:"receiverId"`
	SenderId   int64  `json:"senderId"`
	Type       string `json:"type"`
	Content    string `json:"content"`
	Time       string `json:"time"`
}

type SocketReq struct {
}

type SocketResp struct {
}

type GetMessageRequest struct {
	ReceiverId int64 `path:"receiverId"`
}

type GetMessageResponse struct {
	Message []Message `json:"message"`
}
