// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.22.2
// source: likecenter.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Likecenter_PostLike_FullMethodName   = "/pb.likecenter/postLike"
	Likecenter_CheckLike_FullMethodName  = "/pb.likecenter/checkLike"
	Likecenter_CancelLike_FullMethodName = "/pb.likecenter/cancelLike"
	Likecenter_GetLikes_FullMethodName   = "/pb.likecenter/getLikes"
)

// LikecenterClient is the client API for Likecenter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LikecenterClient interface {
	PostLike(ctx context.Context, in *LikeRequest, opts ...grpc.CallOption) (*LikeResponse, error)
	CheckLike(ctx context.Context, in *CheckLikeRequest, opts ...grpc.CallOption) (*CheckLikeResponse, error)
	CancelLike(ctx context.Context, in *CancelLikeRequest, opts ...grpc.CallOption) (*CancelLikeResponse, error)
	GetLikes(ctx context.Context, in *GetLikesRequest, opts ...grpc.CallOption) (*GetLikesResponse, error)
}

type likecenterClient struct {
	cc grpc.ClientConnInterface
}

func NewLikecenterClient(cc grpc.ClientConnInterface) LikecenterClient {
	return &likecenterClient{cc}
}

func (c *likecenterClient) PostLike(ctx context.Context, in *LikeRequest, opts ...grpc.CallOption) (*LikeResponse, error) {
	out := new(LikeResponse)
	err := c.cc.Invoke(ctx, Likecenter_PostLike_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *likecenterClient) CheckLike(ctx context.Context, in *CheckLikeRequest, opts ...grpc.CallOption) (*CheckLikeResponse, error) {
	out := new(CheckLikeResponse)
	err := c.cc.Invoke(ctx, Likecenter_CheckLike_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *likecenterClient) CancelLike(ctx context.Context, in *CancelLikeRequest, opts ...grpc.CallOption) (*CancelLikeResponse, error) {
	out := new(CancelLikeResponse)
	err := c.cc.Invoke(ctx, Likecenter_CancelLike_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *likecenterClient) GetLikes(ctx context.Context, in *GetLikesRequest, opts ...grpc.CallOption) (*GetLikesResponse, error) {
	out := new(GetLikesResponse)
	err := c.cc.Invoke(ctx, Likecenter_GetLikes_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LikecenterServer is the server API for Likecenter service.
// All implementations must embed UnimplementedLikecenterServer
// for forward compatibility
type LikecenterServer interface {
	PostLike(context.Context, *LikeRequest) (*LikeResponse, error)
	CheckLike(context.Context, *CheckLikeRequest) (*CheckLikeResponse, error)
	CancelLike(context.Context, *CancelLikeRequest) (*CancelLikeResponse, error)
	GetLikes(context.Context, *GetLikesRequest) (*GetLikesResponse, error)
	mustEmbedUnimplementedLikecenterServer()
}

// UnimplementedLikecenterServer must be embedded to have forward compatible implementations.
type UnimplementedLikecenterServer struct {
}

func (UnimplementedLikecenterServer) PostLike(context.Context, *LikeRequest) (*LikeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostLike not implemented")
}
func (UnimplementedLikecenterServer) CheckLike(context.Context, *CheckLikeRequest) (*CheckLikeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckLike not implemented")
}
func (UnimplementedLikecenterServer) CancelLike(context.Context, *CancelLikeRequest) (*CancelLikeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelLike not implemented")
}
func (UnimplementedLikecenterServer) GetLikes(context.Context, *GetLikesRequest) (*GetLikesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLikes not implemented")
}
func (UnimplementedLikecenterServer) mustEmbedUnimplementedLikecenterServer() {}

// UnsafeLikecenterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LikecenterServer will
// result in compilation errors.
type UnsafeLikecenterServer interface {
	mustEmbedUnimplementedLikecenterServer()
}

func RegisterLikecenterServer(s grpc.ServiceRegistrar, srv LikecenterServer) {
	s.RegisterService(&Likecenter_ServiceDesc, srv)
}

func _Likecenter_PostLike_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LikeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LikecenterServer).PostLike(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Likecenter_PostLike_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LikecenterServer).PostLike(ctx, req.(*LikeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Likecenter_CheckLike_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckLikeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LikecenterServer).CheckLike(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Likecenter_CheckLike_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LikecenterServer).CheckLike(ctx, req.(*CheckLikeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Likecenter_CancelLike_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelLikeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LikecenterServer).CancelLike(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Likecenter_CancelLike_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LikecenterServer).CancelLike(ctx, req.(*CancelLikeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Likecenter_GetLikes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLikesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LikecenterServer).GetLikes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Likecenter_GetLikes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LikecenterServer).GetLikes(ctx, req.(*GetLikesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Likecenter_ServiceDesc is the grpc.ServiceDesc for Likecenter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Likecenter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.likecenter",
	HandlerType: (*LikecenterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "postLike",
			Handler:    _Likecenter_PostLike_Handler,
		},
		{
			MethodName: "checkLike",
			Handler:    _Likecenter_CheckLike_Handler,
		},
		{
			MethodName: "cancelLike",
			Handler:    _Likecenter_CancelLike_Handler,
		},
		{
			MethodName: "getLikes",
			Handler:    _Likecenter_GetLikes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "likecenter.proto",
}
