// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.22.2
// source: chat.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Chatcenter_GetMessage_FullMethodName         = "/pb.chatcenter/getMessage"
	Chatcenter_SaveMessageRequest_FullMethodName = "/pb.chatcenter/saveMessageRequest"
	Chatcenter_GetLastMessage_FullMethodName     = "/pb.chatcenter/getLastMessage"
)

// ChatcenterClient is the client API for Chatcenter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChatcenterClient interface {
	GetMessage(ctx context.Context, in *GetMessageRequest, opts ...grpc.CallOption) (*GetMessageResponse, error)
	SaveMessageRequest(ctx context.Context, in *SaveMessageRequest, opts ...grpc.CallOption) (*SaveMessageResponse, error)
	GetLastMessage(ctx context.Context, in *LastMessageRequest, opts ...grpc.CallOption) (*LastMessageResponse, error)
}

type chatcenterClient struct {
	cc grpc.ClientConnInterface
}

func NewChatcenterClient(cc grpc.ClientConnInterface) ChatcenterClient {
	return &chatcenterClient{cc}
}

func (c *chatcenterClient) GetMessage(ctx context.Context, in *GetMessageRequest, opts ...grpc.CallOption) (*GetMessageResponse, error) {
	out := new(GetMessageResponse)
	err := c.cc.Invoke(ctx, Chatcenter_GetMessage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatcenterClient) SaveMessageRequest(ctx context.Context, in *SaveMessageRequest, opts ...grpc.CallOption) (*SaveMessageResponse, error) {
	out := new(SaveMessageResponse)
	err := c.cc.Invoke(ctx, Chatcenter_SaveMessageRequest_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatcenterClient) GetLastMessage(ctx context.Context, in *LastMessageRequest, opts ...grpc.CallOption) (*LastMessageResponse, error) {
	out := new(LastMessageResponse)
	err := c.cc.Invoke(ctx, Chatcenter_GetLastMessage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatcenterServer is the server API for Chatcenter service.
// All implementations must embed UnimplementedChatcenterServer
// for forward compatibility
type ChatcenterServer interface {
	GetMessage(context.Context, *GetMessageRequest) (*GetMessageResponse, error)
	SaveMessageRequest(context.Context, *SaveMessageRequest) (*SaveMessageResponse, error)
	GetLastMessage(context.Context, *LastMessageRequest) (*LastMessageResponse, error)
	mustEmbedUnimplementedChatcenterServer()
}

// UnimplementedChatcenterServer must be embedded to have forward compatible implementations.
type UnimplementedChatcenterServer struct {
}

func (UnimplementedChatcenterServer) GetMessage(context.Context, *GetMessageRequest) (*GetMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMessage not implemented")
}
func (UnimplementedChatcenterServer) SaveMessageRequest(context.Context, *SaveMessageRequest) (*SaveMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveMessageRequest not implemented")
}
func (UnimplementedChatcenterServer) GetLastMessage(context.Context, *LastMessageRequest) (*LastMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLastMessage not implemented")
}
func (UnimplementedChatcenterServer) mustEmbedUnimplementedChatcenterServer() {}

// UnsafeChatcenterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatcenterServer will
// result in compilation errors.
type UnsafeChatcenterServer interface {
	mustEmbedUnimplementedChatcenterServer()
}

func RegisterChatcenterServer(s grpc.ServiceRegistrar, srv ChatcenterServer) {
	s.RegisterService(&Chatcenter_ServiceDesc, srv)
}

func _Chatcenter_GetMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatcenterServer).GetMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chatcenter_GetMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatcenterServer).GetMessage(ctx, req.(*GetMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chatcenter_SaveMessageRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatcenterServer).SaveMessageRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chatcenter_SaveMessageRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatcenterServer).SaveMessageRequest(ctx, req.(*SaveMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chatcenter_GetLastMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LastMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatcenterServer).GetLastMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chatcenter_GetLastMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatcenterServer).GetLastMessage(ctx, req.(*LastMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Chatcenter_ServiceDesc is the grpc.ServiceDesc for Chatcenter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Chatcenter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.chatcenter",
	HandlerType: (*ChatcenterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getMessage",
			Handler:    _Chatcenter_GetMessage_Handler,
		},
		{
			MethodName: "saveMessageRequest",
			Handler:    _Chatcenter_SaveMessageRequest_Handler,
		},
		{
			MethodName: "getLastMessage",
			Handler:    _Chatcenter_GetLastMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chat.proto",
}
