syntax = "proto3";

option go_package = "./pb";
package pb;


message Message {
  int64 Id = 1;
  int64 SenderId = 2;
  int64 ReceiverId = 3;
  string Type = 4;
  string Content = 5;
  string Time = 6;
}

message GetMessageRequest{
    int64 SenderId = 1;
    int64 ReceiverId = 2;
}

message GetMessageResponse{
  repeated Message message = 1;
}

message SaveMessageRequest{
   int64 SenderId = 2;
   int64 ReceiverId = 3;
   string Type = 4;
   string Content = 5;
//   string Time = 6;
}


message SaveMessageResponse{
  Message Message = 1;
}

message LastMessageRequest{
  int64 SenderId = 1;
  int64 ReceiverId = 2;
}

message LastMessageResponse{
 string Content = 1;
 string Type = 2;
 string Time = 3;
}

service chatcenter{
  rpc getMessage(GetMessageRequest)returns(GetMessageResponse);
  rpc saveMessageRequest(SaveMessageRequest)returns(SaveMessageResponse);
  rpc getLastMessage(LastMessageRequest)returns(LastMessageResponse);
}