// Code generated by goctl. DO NOT EDIT.
// Source: comment.proto

package server

import (
	"context"

	"LingXi/app/comment/cmd/rpc/internal/logic"
	"LingXi/app/comment/cmd/rpc/internal/svc"
	"LingXi/app/comment/cmd/rpc/pb"
)

type CommentCenterServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedCommentCenterServer
}

func NewCommentCenterServer(svcCtx *svc.ServiceContext) *CommentCenterServer {
	return &CommentCenterServer{
		svcCtx: svcCtx,
	}
}

func (s *CommentCenterServer) PostComment(ctx context.Context, in *pb.CommentRequest) (*pb.CommentResponse, error) {
	l := logic.NewPostCommentLogic(ctx, s.svcCtx)
	return l.PostComment(in)
}

func (s *CommentCenterServer) GetComments(ctx context.Context, in *pb.GetCommentRequest) (*pb.GetCommentResponse, error) {
	l := logic.NewGetCommentsLogic(ctx, s.svcCtx)
	return l.GetComments(in)
}

func (s *CommentCenterServer) DeleteComment(ctx context.Context, in *pb.DeleteCommentRequest) (*pb.DeleteCommentResponse, error) {
	l := logic.NewDeleteCommentLogic(ctx, s.svcCtx)
	return l.DeleteComment(in)
}
