// Code generated by goctl. DO NOT EDIT.
// Source: imagecenter.proto

package imagecenter

import (
	"context"

	"LingXi/app/images/cmd/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	DeleteImageRequest   = pb.DeleteImageRequest
	DeleteImageResponse  = pb.DeleteImageResponse
	GetAllImagesRequest  = pb.GetAllImagesRequest
	GetAllImagesResponse = pb.GetAllImagesResponse
	GetDetailRequest     = pb.GetDetailRequest
	GetDetailResponse    = pb.GetDetailResponse
	GetOneImageRequest   = pb.GetOneImageRequest
	GetOneImageResponse  = pb.GetOneImageResponse
	Image                = pb.Image
	PostImageRequest     = pb.PostImageRequest
	PostImageResponse    = pb.PostImageResponse

	ImageCenter interface {
		PostImage(ctx context.Context, in *PostImageRequest, opts ...grpc.CallOption) (*PostImageResponse, error)
		GetAllImages(ctx context.Context, in *GetAllImagesRequest, opts ...grpc.CallOption) (*GetAllImagesResponse, error)
		GetDetail(ctx context.Context, in *GetDetailRequest, opts ...grpc.CallOption) (*GetDetailResponse, error)
		DeleteImage(ctx context.Context, in *DeleteImageRequest, opts ...grpc.CallOption) (*DeleteImageResponse, error)
		GetOneImage(ctx context.Context, in *GetOneImageRequest, opts ...grpc.CallOption) (*GetOneImageResponse, error)
	}

	defaultImageCenter struct {
		cli zrpc.Client
	}
)

func NewImageCenter(cli zrpc.Client) ImageCenter {
	return &defaultImageCenter{
		cli: cli,
	}
}

func (m *defaultImageCenter) PostImage(ctx context.Context, in *PostImageRequest, opts ...grpc.CallOption) (*PostImageResponse, error) {
	client := pb.NewImageCenterClient(m.cli.Conn())
	return client.PostImage(ctx, in, opts...)
}

func (m *defaultImageCenter) GetAllImages(ctx context.Context, in *GetAllImagesRequest, opts ...grpc.CallOption) (*GetAllImagesResponse, error) {
	client := pb.NewImageCenterClient(m.cli.Conn())
	return client.GetAllImages(ctx, in, opts...)
}

func (m *defaultImageCenter) GetDetail(ctx context.Context, in *GetDetailRequest, opts ...grpc.CallOption) (*GetDetailResponse, error) {
	client := pb.NewImageCenterClient(m.cli.Conn())
	return client.GetDetail(ctx, in, opts...)
}

func (m *defaultImageCenter) DeleteImage(ctx context.Context, in *DeleteImageRequest, opts ...grpc.CallOption) (*DeleteImageResponse, error) {
	client := pb.NewImageCenterClient(m.cli.Conn())
	return client.DeleteImage(ctx, in, opts...)
}

func (m *defaultImageCenter) GetOneImage(ctx context.Context, in *GetOneImageRequest, opts ...grpc.CallOption) (*GetOneImageResponse, error) {
	client := pb.NewImageCenterClient(m.cli.Conn())
	return client.GetOneImage(ctx, in, opts...)
}
