// Code generated by goctl. DO NOT EDIT.
// Source: tweetcenter.proto

package server

import (
	"context"

	"LingXi/app/tweet/cmd/rpc/internal/logic"
	"LingXi/app/tweet/cmd/rpc/internal/svc"
	"LingXi/app/tweet/cmd/rpc/pb"
)

type TweetCenterServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedTweetCenterServer
}

func NewTweetCenterServer(svcCtx *svc.ServiceContext) *TweetCenterServer {
	return &TweetCenterServer{
		svcCtx: svcCtx,
	}
}

func (s *TweetCenterServer) PostTweet(ctx context.Context, in *pb.TweetRequest) (*pb.TweetResponse, error) {
	l := logic.NewPostTweetLogic(ctx, s.svcCtx)
	return l.PostTweet(in)
}
