// Code generated by goctl. DO NOT EDIT.
// Source: tweetcenter.proto

package tweetcenter

import (
	"context"

	"LingXi/app/tweet/cmd/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Tweet         = pb.Tweet
	TweetRequest  = pb.TweetRequest
	TweetResponse = pb.TweetResponse

	TweetCenter interface {
		PostTweet(ctx context.Context, in *TweetRequest, opts ...grpc.CallOption) (*TweetResponse, error)
	}

	defaultTweetCenter struct {
		cli zrpc.Client
	}
)

func NewTweetCenter(cli zrpc.Client) TweetCenter {
	return &defaultTweetCenter{
		cli: cli,
	}
}

func (m *defaultTweetCenter) PostTweet(ctx context.Context, in *TweetRequest, opts ...grpc.CallOption) (*TweetResponse, error) {
	client := pb.NewTweetCenterClient(m.cli.Conn())
	return client.PostTweet(ctx, in, opts...)
}
