// Code generated by goctl. DO NOT EDIT.
package handler

import (

	"net/http"

	chat "LingXi/app/chat/cmd/api/internal/handler/chat"

	"LingXi/app/chat/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/chat/ws",
				Handler: chat.ChatHandler(serverCtx),
			},
		},
		rest.WithPrefix("/chatcenter/v1"),
	)
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/chat/msg:receiverId",
				Handler: chat.GetMessageHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/chatcenter/v1"),
	)
}

