// Code generated by goctl. DO NOT EDIT.
// Source: usercenter.proto

package server

import (
	"context"

	"LingXi/app/usercenter/cmd/rpc/internal/logic"
	"LingXi/app/usercenter/cmd/rpc/internal/svc"
	"LingXi/app/usercenter/cmd/rpc/pb"
)

type UserCenterServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedUserCenterServer
}

func NewUserCenterServer(svcCtx *svc.ServiceContext) *UserCenterServer {
	return &UserCenterServer{
		svcCtx: svcCtx,
	}
}

func (s *UserCenterServer) Login(ctx context.Context, in *pb.LoginReq) (*pb.LoginResp, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UserCenterServer) Register(ctx context.Context, in *pb.RegisterReq) (*pb.RegisterResp, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UserCenterServer) GetVerification(ctx context.Context, in *pb.VerificationReq) (*pb.VerificationResp, error) {
	l := logic.NewGetVerificationLogic(ctx, s.svcCtx)
	return l.GetVerification(in)
}

func (s *UserCenterServer) GetUserInfo(ctx context.Context, in *pb.UserInfoReq) (*pb.UserInfoResp, error) {
	l := logic.NewGetUserInfoLogic(ctx, s.svcCtx)
	return l.GetUserInfo(in)
}

func (s *UserCenterServer) GenerateToken(ctx context.Context, in *pb.GenerateTokenReq) (*pb.GenerateTokenResp, error) {
	l := logic.NewGenerateTokenLogic(ctx, s.svcCtx)
	return l.GenerateToken(in)
}

func (s *UserCenterServer) UpdateInfo(ctx context.Context, in *pb.UpdateInfoReq) (*pb.UpdateInfoResp, error) {
	l := logic.NewUpdateInfoLogic(ctx, s.svcCtx)
	return l.UpdateInfo(in)
}

func (s *UserCenterServer) UpdatePSW(ctx context.Context, in *pb.UpdatePSWReq) (*pb.UpdatePSWResp, error) {
	l := logic.NewUpdatePSWLogic(ctx, s.svcCtx)
	return l.UpdatePSW(in)
}

func (s *UserCenterServer) GiveUserAuth(ctx context.Context, in *pb.AuthReq) (*pb.AuthResp, error) {
	l := logic.NewGiveUserAuthLogic(ctx, s.svcCtx)
	return l.GiveUserAuth(in)
}
