// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"time"

	"github.com/SpectatorNan/gorm-zero/gormc"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"gorm.io/gorm"
)

var (
	cachePostIdPrefix = "cache:post:id:"
)

type (
	postModel interface {
		Insert(ctx context.Context, tx *gorm.DB, data *Post) error

		FindOne(ctx context.Context, id int64) (*Post, error)
		Update(ctx context.Context, tx *gorm.DB, data *Post) error

		Delete(ctx context.Context, tx *gorm.DB, id int64) error
		Transaction(ctx context.Context, fn func(db *gorm.DB) error) error
	}

	defaultPostModel struct {
		gormc.CachedConn
		table string
	}

	Post struct {
		Id          int64        `gorm:"column:id"`
		PublisherId int64        `gorm:"column:publisher_id"`
		Category    string       `gorm:"column:category"`
		Content     string       `gorm:"column:content"`
		ViewNum     int64        `gorm:"column:view_num"`
		LikeNum     int64        `gorm:"column:like_num"`
		CommentNum  int64        `gorm:"column:comment_num"`
		CreateTime  time.Time    `gorm:"column:create_time"`
		UpdateTime  time.Time    `gorm:"column:update_time"`
		DeleteTime  sql.NullTime `gorm:"column:delete_time"`
	}
)

func (Post) TableName() string {
	return "`post`"
}

func newPostModel(conn *gorm.DB, c cache.CacheConf) *defaultPostModel {
	return &defaultPostModel{
		CachedConn: gormc.NewConn(conn, c),
		table:      "`post`",
	}
}

func (m *defaultPostModel) Insert(ctx context.Context, tx *gorm.DB, data *Post) error {

	err := m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Save(&data).Error
	}, m.getCacheKeys(data)...)
	return err
}

func (m *defaultPostModel) FindOne(ctx context.Context, id int64) (*Post, error) {
	postIdKey := fmt.Sprintf("%s%v", cachePostIdPrefix, id)
	var resp Post
	err := m.QueryCtx(ctx, &resp, postIdKey, func(conn *gorm.DB, v interface{}) error {
		return conn.Model(&Post{}).Where("`id` = ? and `delete_time` is null", id).First(&resp).Error
	})
	switch err {
	case nil:
		return &resp, nil
	case gormc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPostModel) Update(ctx context.Context, tx *gorm.DB, data *Post) error {
	old, err := m.FindOne(ctx, data.Id)
	if err != nil && err != ErrNotFound {
		return err
	}
	err = m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Save(data).Error
	}, m.getCacheKeys(old)...)
	return err
}

func (m *defaultPostModel) getCacheKeys(data *Post) []string {
	if data == nil {
		return []string{}
	}
	postIdKey := fmt.Sprintf("%s%v", cachePostIdPrefix, data.Id)
	cacheKeys := []string{
		postIdKey,
	}
	cacheKeys = append(cacheKeys, m.customCacheKeys(data)...)
	return cacheKeys
}

func (m *defaultPostModel) Delete(ctx context.Context, tx *gorm.DB, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		if err == ErrNotFound {
			return nil
		}
		return err
	}
	err = m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Delete(&Post{}, id).Error
	}, m.getCacheKeys(data)...)
	return err
}

func (m *defaultPostModel) Transaction(ctx context.Context, fn func(db *gorm.DB) error) error {
	return m.TransactCtx(ctx, fn)
}

func (m *defaultPostModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cachePostIdPrefix, primary)
}

func (m *defaultPostModel) queryPrimary(conn *gorm.DB, v, primary interface{}) error {
	return conn.Model(&Post{}).Where("`id` = ?", primary).Take(v).Error
}
