// Code generated by goctl. DO NOT EDIT.
// Source: starcenter.proto

package server

import (
	"context"

	"LingXi/app/star/cmd/rpc/internal/logic"
	"LingXi/app/star/cmd/rpc/internal/svc"
	"LingXi/app/star/cmd/rpc/pb"
)

type StarcenterServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedStarcenterServer
}

func NewStarcenterServer(svcCtx *svc.ServiceContext) *StarcenterServer {
	return &StarcenterServer{
		svcCtx: svcCtx,
	}
}

func (s *StarcenterServer) EnterStar(ctx context.Context, in *pb.EnterStarRequest) (*pb.EnterStarResponse, error) {
	l := logic.NewEnterStarLogic(ctx, s.svcCtx)
	return l.EnterStar(in)
}

func (s *StarcenterServer) MyStar(ctx context.Context, in *pb.MyStarRequest) (*pb.MyStarResponse, error) {
	l := logic.NewMyStarLogic(ctx, s.svcCtx)
	return l.MyStar(in)
}

func (s *StarcenterServer) StarDetail(ctx context.Context, in *pb.StarDetailRequest) (*pb.StarDetailResponse, error) {
	l := logic.NewStarDetailLogic(ctx, s.svcCtx)
	return l.StarDetail(in)
}

func (s *StarcenterServer) IfEnter(ctx context.Context, in *pb.IfEnterRequest) (*pb.IfEnterResponse, error) {
	l := logic.NewIfEnterLogic(ctx, s.svcCtx)
	return l.IfEnter(in)
}
