// Code generated by goctl. DO NOT EDIT.
package types

type UserInfo struct {
	UserId      int64       `json:"userId"`
	UserName    string      `json:"userName"`
	Avatar      string      `json:"avatar"`
	LastMessage LastMessage `json:"lastMessage"`
}

type LastMessage struct {
	Content string `json:"content"`
	Type    string `json:"type"`
	Time    string `json:"time"`
}

type Connection struct {
	VolunteerId int64 `json:"volunteerId"`
	UserId      int64 `json:"userId"`
}

type AddConnectionRequest struct {
	UserId int64 `json:"userId"`
}

type AddConnectionResponse struct {
	Connection Connection `json:"connection"`
}

type GetConnectionRequest struct {
}

type GetConnectionResponse struct {
	UserInfo []UserInfo `json:"userInfo"`
}
