// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"fmt"

	"github.com/SpectatorNan/gorm-zero/gormc"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"gorm.io/gorm"
)

var (
	cacheTweetIdPrefix = "cache:tweet:id:"
)

type (
	tweetModel interface {
		Insert(ctx context.Context, tx *gorm.DB, data *Tweet) error

		FindOne(ctx context.Context, id int64) (*Tweet, error)
		Update(ctx context.Context, tx *gorm.DB, data *Tweet) error

		Delete(ctx context.Context, tx *gorm.DB, id int64) error
		Transaction(ctx context.Context, fn func(db *gorm.DB) error) error
	}

	defaultTweetModel struct {
		gormc.CachedConn
		table string
	}

	Tweet struct {
		Id          int64  `gorm:"column:id"`
		PublisherId int64  `gorm:"column:publisher_id"`
		Content     string `gorm:"column:content"`
		ViewNum     string `gorm:"column:view_num"`
		LikeNum     int64  `gorm:"column:like_num"`
		CommentNum  int64  `gorm:"column:comment_num"`
	}
)

func (Tweet) TableName() string {
	return "`tweet`"
}

func newTweetModel(conn *gorm.DB, c cache.CacheConf) *defaultTweetModel {
	return &defaultTweetModel{
		CachedConn: gormc.NewConn(conn, c),
		table:      "`tweet`",
	}
}

func (m *defaultTweetModel) Insert(ctx context.Context, tx *gorm.DB, data *Tweet) error {

	err := m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Save(&data).Error
	}, m.getCacheKeys(data)...)
	return err
}

func (m *defaultTweetModel) FindOne(ctx context.Context, id int64) (*Tweet, error) {
	tweetIdKey := fmt.Sprintf("%s%v", cacheTweetIdPrefix, id)
	var resp Tweet
	err := m.QueryCtx(ctx, &resp, tweetIdKey, func(conn *gorm.DB, v interface{}) error {
		return conn.Model(&Tweet{}).Where("`id` = ?", id).First(&resp).Error
	})
	switch err {
	case nil:
		return &resp, nil
	case gormc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTweetModel) Update(ctx context.Context, tx *gorm.DB, data *Tweet) error {
	old, err := m.FindOne(ctx, data.Id)
	if err != nil && err != ErrNotFound {
		return err
	}
	err = m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Save(data).Error
	}, m.getCacheKeys(old)...)
	return err
}

func (m *defaultTweetModel) getCacheKeys(data *Tweet) []string {
	if data == nil {
		return []string{}
	}
	tweetIdKey := fmt.Sprintf("%s%v", cacheTweetIdPrefix, data.Id)
	cacheKeys := []string{
		tweetIdKey,
	}
	cacheKeys = append(cacheKeys, m.customCacheKeys(data)...)
	return cacheKeys
}

func (m *defaultTweetModel) Delete(ctx context.Context, tx *gorm.DB, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		if err == ErrNotFound {
			return nil
		}
		return err
	}
	err = m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Delete(&Tweet{}, id).Error
	}, m.getCacheKeys(data)...)
	return err
}

func (m *defaultTweetModel) Transaction(ctx context.Context, fn func(db *gorm.DB) error) error {
	return m.TransactCtx(ctx, fn)
}

func (m *defaultTweetModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheTweetIdPrefix, primary)
}

func (m *defaultTweetModel) queryPrimary(conn *gorm.DB, v, primary interface{}) error {
	return conn.Model(&Tweet{}).Where("`id` = ?", primary).Take(v).Error
}
