// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"fmt"

	"github.com/SpectatorNan/gorm-zero/gormc"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"gorm.io/gorm"
)

var (
	cacheTweetImageIdPrefix = "cache:tweetImage:id:"
)

type (
	tweetImageModel interface {
		Insert(ctx context.Context, tx *gorm.DB, data *TweetImage) error

		FindOne(ctx context.Context, id int64) (*TweetImage, error)
		Update(ctx context.Context, tx *gorm.DB, data *TweetImage) error

		Delete(ctx context.Context, tx *gorm.DB, id int64) error
		Transaction(ctx context.Context, fn func(db *gorm.DB) error) error
	}

	defaultTweetImageModel struct {
		gormc.CachedConn
		table string
	}

	TweetImage struct {
		Id     int64          `gorm:"column:id"`
		PostId sql.NullInt64  `gorm:"column:post_id"`
		Url    sql.NullString `gorm:"column:url"`
	}
)

func (TweetImage) TableName() string {
	return "`tweet_image`"
}

func newTweetImageModel(conn *gorm.DB, c cache.CacheConf) *defaultTweetImageModel {
	return &defaultTweetImageModel{
		CachedConn: gormc.NewConn(conn, c),
		table:      "`tweet_image`",
	}
}

func (m *defaultTweetImageModel) Insert(ctx context.Context, tx *gorm.DB, data *TweetImage) error {

	err := m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Save(&data).Error
	}, m.getCacheKeys(data)...)
	return err
}

func (m *defaultTweetImageModel) FindOne(ctx context.Context, id int64) (*TweetImage, error) {
	tweetImageIdKey := fmt.Sprintf("%s%v", cacheTweetImageIdPrefix, id)
	var resp TweetImage
	err := m.QueryCtx(ctx, &resp, tweetImageIdKey, func(conn *gorm.DB, v interface{}) error {
		return conn.Model(&TweetImage{}).Where("`id` = ?", id).First(&resp).Error
	})
	switch err {
	case nil:
		return &resp, nil
	case gormc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTweetImageModel) Update(ctx context.Context, tx *gorm.DB, data *TweetImage) error {
	old, err := m.FindOne(ctx, data.Id)
	if err != nil && err != ErrNotFound {
		return err
	}
	err = m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Save(data).Error
	}, m.getCacheKeys(old)...)
	return err
}

func (m *defaultTweetImageModel) getCacheKeys(data *TweetImage) []string {
	if data == nil {
		return []string{}
	}
	tweetImageIdKey := fmt.Sprintf("%s%v", cacheTweetImageIdPrefix, data.Id)
	cacheKeys := []string{
		tweetImageIdKey,
	}
	cacheKeys = append(cacheKeys, m.customCacheKeys(data)...)
	return cacheKeys
}

func (m *defaultTweetImageModel) Delete(ctx context.Context, tx *gorm.DB, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		if err == ErrNotFound {
			return nil
		}
		return err
	}
	err = m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Delete(&TweetImage{}, id).Error
	}, m.getCacheKeys(data)...)
	return err
}

func (m *defaultTweetImageModel) Transaction(ctx context.Context, fn func(db *gorm.DB) error) error {
	return m.TransactCtx(ctx, fn)
}

func (m *defaultTweetImageModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheTweetImageIdPrefix, primary)
}

func (m *defaultTweetImageModel) queryPrimary(conn *gorm.DB, v, primary interface{}) error {
	return conn.Model(&TweetImage{}).Where("`id` = ?", primary).Take(v).Error
}
