// Code generated by goctl. DO NOT EDIT.
package types

type Tweet struct {
	Id          int64  `json:"id"`
	PublisherId int64  `json:"publisherId"`
	Content     string `json:"content"`
}

type TweetImage struct {
	Id      int64  `json:"id"`
	TweetId int64  `json:"tweetId"`
	Url     string `json:"url"`
}

type TweetRequest struct {
	Content string `json:"content"`
}

type TweetResponse struct {
	Tweet Tweet `json:"tweet.sql"`
}

type TweetImageRequest struct {
	TweetId int64  `json:"tweetId"`
	Url     string `json:"url"`
}

type TweetImageResponse struct {
	TweetImage TweetImage `json:"tweetImage"`
}
