// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"time"

	"github.com/SpectatorNan/gorm-zero/gormc"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"gorm.io/gorm"
)

var (
	cacheConnectionIdPrefix = "cache:connection:id:"
)

type (
	connectionModel interface {
		Insert(ctx context.Context, tx *gorm.DB, data *Connection) error

		FindOne(ctx context.Context, id int64) (*Connection, error)
		Update(ctx context.Context, tx *gorm.DB, data *Connection) error

		Delete(ctx context.Context, tx *gorm.DB, id int64) error
		Transaction(ctx context.Context, fn func(db *gorm.DB) error) error
	}

	defaultConnectionModel struct {
		gormc.CachedConn
		table string
	}

	Connection struct {
		Id          int64        `gorm:"column:id"`
		VolunteerId int64        `gorm:"column:volunteer_id"`
		UserId      int64        `gorm:"column:user_id"`
		Will        int64        `gorm:"column:will"`
		CreateTime  time.Time    `gorm:"column:create_time"`
		UpdateTime  time.Time    `gorm:"column:update_time"`
		DeleteTime  sql.NullTime `gorm:"column:delete_time"`
	}
)

func (Connection) TableName() string {
	return "`connection`"
}

func newConnectionModel(conn *gorm.DB, c cache.CacheConf) *defaultConnectionModel {
	return &defaultConnectionModel{
		CachedConn: gormc.NewConn(conn, c),
		table:      "`connection`",
	}
}

func (m *defaultConnectionModel) Insert(ctx context.Context, tx *gorm.DB, data *Connection) error {

	err := m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Save(&data).Error
	}, m.getCacheKeys(data)...)
	return err
}

func (m *defaultConnectionModel) FindOne(ctx context.Context, id int64) (*Connection, error) {
	connectionIdKey := fmt.Sprintf("%s%v", cacheConnectionIdPrefix, id)
	var resp Connection
	err := m.QueryCtx(ctx, &resp, connectionIdKey, func(conn *gorm.DB, v interface{}) error {
		return conn.Model(&Connection{}).Where("`id` = ?", id).First(&resp).Error
	})
	switch err {
	case nil:
		return &resp, nil
	case gormc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultConnectionModel) Update(ctx context.Context, tx *gorm.DB, data *Connection) error {
	old, err := m.FindOne(ctx, data.Id)
	if err != nil && err != ErrNotFound {
		return err
	}
	err = m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Save(data).Error
	}, m.getCacheKeys(old)...)
	return err
}

func (m *defaultConnectionModel) getCacheKeys(data *Connection) []string {
	if data == nil {
		return []string{}
	}
	connectionIdKey := fmt.Sprintf("%s%v", cacheConnectionIdPrefix, data.Id)
	cacheKeys := []string{
		connectionIdKey,
	}
	cacheKeys = append(cacheKeys, m.customCacheKeys(data)...)
	return cacheKeys
}

func (m *defaultConnectionModel) Delete(ctx context.Context, tx *gorm.DB, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		if err == ErrNotFound {
			return nil
		}
		return err
	}
	err = m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Delete(&Connection{}, id).Error
	}, m.getCacheKeys(data)...)
	return err
}

func (m *defaultConnectionModel) Transaction(ctx context.Context, fn func(db *gorm.DB) error) error {
	return m.TransactCtx(ctx, fn)
}

func (m *defaultConnectionModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheConnectionIdPrefix, primary)
}

func (m *defaultConnectionModel) queryPrimary(conn *gorm.DB, v, primary interface{}) error {
	return conn.Model(&Connection{}).Where("`id` = ?", primary).Take(v).Error
}
