// Code generated by goctl. DO NOT EDIT.
// Source: likecenter.proto

package server

import (
	"context"

	"LingXi/app/like/cmd/rpc/internal/logic"
	"LingXi/app/like/cmd/rpc/internal/svc"
	"LingXi/app/like/cmd/rpc/pb"
)

type LikecenterServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedLikecenterServer
}

func NewLikecenterServer(svcCtx *svc.ServiceContext) *LikecenterServer {
	return &LikecenterServer{
		svcCtx: svcCtx,
	}
}

func (s *LikecenterServer) PostLike(ctx context.Context, in *pb.LikeRequest) (*pb.LikeResponse, error) {
	l := logic.NewPostLikeLogic(ctx, s.svcCtx)
	return l.PostLike(in)
}

func (s *LikecenterServer) CheckLike(ctx context.Context, in *pb.CheckLikeRequest) (*pb.CheckLikeResponse, error) {
	l := logic.NewCheckLikeLogic(ctx, s.svcCtx)
	return l.CheckLike(in)
}

func (s *LikecenterServer) CancelLike(ctx context.Context, in *pb.CancelLikeRequest) (*pb.CancelLikeResponse, error) {
	l := logic.NewCancelLikeLogic(ctx, s.svcCtx)
	return l.CancelLike(in)
}

func (s *LikecenterServer) GetLikes(ctx context.Context, in *pb.GetLikesRequest) (*pb.GetLikesResponse, error) {
	l := logic.NewGetLikesLogic(ctx, s.svcCtx)
	return l.GetLikes(in)
}
