// Code generated by goctl. DO NOT EDIT.
// Source: connectioncenter.proto

package connectioncenter

import (
	"context"

	"LingXi/app/connection/cmd/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddConnectionRequest    = pb.AddConnectionRequest
	AddConnectionResponse   = pb.AddConnectionResponse
	CheckConnectionRequest  = pb.CheckConnectionRequest
	CheckConnectionResponse = pb.CheckConnectionResponse
	UserInfo                = pb.UserInfo

	Connectioncenter interface {
		AddConnection(ctx context.Context, in *AddConnectionRequest, opts ...grpc.CallOption) (*AddConnectionResponse, error)
		CheckConnection(ctx context.Context, in *CheckConnectionRequest, opts ...grpc.CallOption) (*CheckConnectionResponse, error)
	}

	defaultConnectioncenter struct {
		cli zrpc.Client
	}
)

func NewConnectioncenter(cli zrpc.Client) Connectioncenter {
	return &defaultConnectioncenter{
		cli: cli,
	}
}

func (m *defaultConnectioncenter) AddConnection(ctx context.Context, in *AddConnectionRequest, opts ...grpc.CallOption) (*AddConnectionResponse, error) {
	client := pb.NewConnectioncenterClient(m.cli.Conn())
	return client.AddConnection(ctx, in, opts...)
}

func (m *defaultConnectioncenter) CheckConnection(ctx context.Context, in *CheckConnectionRequest, opts ...grpc.CallOption) (*CheckConnectionResponse, error) {
	client := pb.NewConnectioncenterClient(m.cli.Conn())
	return client.CheckConnection(ctx, in, opts...)
}
