// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.22.2
// source: connectioncenter.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Connectioncenter_AddConnection_FullMethodName   = "/pb.connectioncenter/addConnection"
	Connectioncenter_CheckConnection_FullMethodName = "/pb.connectioncenter/checkConnection"
)

// ConnectioncenterClient is the client API for Connectioncenter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConnectioncenterClient interface {
	AddConnection(ctx context.Context, in *AddConnectionRequest, opts ...grpc.CallOption) (*AddConnectionResponse, error)
	CheckConnection(ctx context.Context, in *CheckConnectionRequest, opts ...grpc.CallOption) (*CheckConnectionResponse, error)
}

type connectioncenterClient struct {
	cc grpc.ClientConnInterface
}

func NewConnectioncenterClient(cc grpc.ClientConnInterface) ConnectioncenterClient {
	return &connectioncenterClient{cc}
}

func (c *connectioncenterClient) AddConnection(ctx context.Context, in *AddConnectionRequest, opts ...grpc.CallOption) (*AddConnectionResponse, error) {
	out := new(AddConnectionResponse)
	err := c.cc.Invoke(ctx, Connectioncenter_AddConnection_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectioncenterClient) CheckConnection(ctx context.Context, in *CheckConnectionRequest, opts ...grpc.CallOption) (*CheckConnectionResponse, error) {
	out := new(CheckConnectionResponse)
	err := c.cc.Invoke(ctx, Connectioncenter_CheckConnection_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConnectioncenterServer is the server API for Connectioncenter service.
// All implementations must embed UnimplementedConnectioncenterServer
// for forward compatibility
type ConnectioncenterServer interface {
	AddConnection(context.Context, *AddConnectionRequest) (*AddConnectionResponse, error)
	CheckConnection(context.Context, *CheckConnectionRequest) (*CheckConnectionResponse, error)
	mustEmbedUnimplementedConnectioncenterServer()
}

// UnimplementedConnectioncenterServer must be embedded to have forward compatible implementations.
type UnimplementedConnectioncenterServer struct {
}

func (UnimplementedConnectioncenterServer) AddConnection(context.Context, *AddConnectionRequest) (*AddConnectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddConnection not implemented")
}
func (UnimplementedConnectioncenterServer) CheckConnection(context.Context, *CheckConnectionRequest) (*CheckConnectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckConnection not implemented")
}
func (UnimplementedConnectioncenterServer) mustEmbedUnimplementedConnectioncenterServer() {}

// UnsafeConnectioncenterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConnectioncenterServer will
// result in compilation errors.
type UnsafeConnectioncenterServer interface {
	mustEmbedUnimplementedConnectioncenterServer()
}

func RegisterConnectioncenterServer(s grpc.ServiceRegistrar, srv ConnectioncenterServer) {
	s.RegisterService(&Connectioncenter_ServiceDesc, srv)
}

func _Connectioncenter_AddConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectioncenterServer).AddConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Connectioncenter_AddConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectioncenterServer).AddConnection(ctx, req.(*AddConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Connectioncenter_CheckConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectioncenterServer).CheckConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Connectioncenter_CheckConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectioncenterServer).CheckConnection(ctx, req.(*CheckConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Connectioncenter_ServiceDesc is the grpc.ServiceDesc for Connectioncenter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Connectioncenter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.connectioncenter",
	HandlerType: (*ConnectioncenterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "addConnection",
			Handler:    _Connectioncenter_AddConnection_Handler,
		},
		{
			MethodName: "checkConnection",
			Handler:    _Connectioncenter_CheckConnection_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "connectioncenter.proto",
}
