// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	posts "LingXi/app/post/cmd/api/internal/handler/posts"
	"LingXi/app/post/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/post",
				Handler: posts.PublishPostHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/all_post",
				Handler: posts.GetPostHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/post/:category",
				Handler: posts.GetCategoryPostHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/post/personal/:category",
				Handler: posts.GetPersonalCategoryPostHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/post/detail/:postId",
				Handler: posts.GetPostDetailsHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/post/:postId",
				Handler: posts.DeletePostHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/post/comment",
				Handler: posts.CommentPostHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/post/comment/:postId",
				Handler: posts.GetPostCommentsHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/post/comment/:commentId",
				Handler: posts.DeletePostCommentsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/post/view",
				Handler: posts.ViewPostHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/post/like",
				Handler: posts.LikePostHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/post/like",
				Handler: posts.CancelLikeHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/post/like/:postId",
				Handler: posts.IfLikeHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/postcenter/v1"),
	)
}
